plugins {
    id("base-conventions")
    id("integration-test-suite")
}

dependencies {
    implementation(libs.bundles.logging)
    implementation(libs.fastutil)
    implementation(libs.guice)
    implementation(libs.jackson.databind)
    implementation(libs.jackson.module.kotlin)
    implementation(projects.api.account)
    implementation(projects.api.cheat)
    implementation(projects.api.combat.combatCommons)
    implementation(projects.api.companion)
    implementation(projects.content.pvmPoints)
    implementation(projects.api.config)
    implementation(projects.api.db)
    implementation(projects.api.death)
    implementation(projects.api.equipmentInstance)
    implementation(projects.api.gameProcess)
    implementation(projects.api.invtx)
    implementation(projects.api.ironman)
    implementation(projects.api.npc)
    implementation(projects.api.player)
    implementation(projects.api.playerOutput)
    implementation(projects.api.pluginCommons)
    implementation(projects.api.random)
    implementation(projects.api.registry)
    implementation(projects.api.repo)
    implementation(projects.api.script)
    implementation(projects.api.scriptAdvanced)
    implementation(projects.api.specials)
    implementation(projects.api.type.typeBuilders)
    implementation(projects.api.type.typeReferences)
    implementation(projects.api.utils.utilsFormat)
    implementation(projects.engine.events)
    implementation(projects.engine.game)
    implementation(projects.engine.module)
    implementation(projects.engine.plugin)

    testImplementation(kotlin("test"))
    integrationImplementation(projects.api.death)
    integrationImplementation(projects.api.npc)
}
