package org.rsmod.content.other.devhub

import org.rsmod.api.config.refs.params
import org.rsmod.content.areas.unforge.teleports.UnforgeTeleports
import org.rsmod.content.areas.unforge.teleports.TeleDest
import org.rsmod.game.type.obj.ObjTypeList
import org.rsmod.map.CoordGrid

/** A single teleport destination shown in the hub's teleport menus. */
data class DevHubTeleport(val label: String, val coords: CoordGrid)

/** A named group of teleports - one spellbook, item, city, activity or combat destination. */
data class DevHubTeleportGroup(val label: String, val teleports: List<DevHubTeleport>)

/**
 * Builds the hub's teleport lists, one per Teleports-tab category row.
 *
 * Spellbook destinations are not hand-authored: `SpellObjs` (api/spells) stamps every teleport
 * spell obj with `params.spell_telecoord`, so the groups are generated by scanning the cache for
 * that param and grouping by `params.spell_spellbook` (0=standard, 1=ancients, 2=lunars,
 * 3=arceuus). Only the four home teleports lack the param and are hand-entered. The remaining
 * categories are the stable Developer Hub destinations used by the server's content and admin
 * workflows; they are intentionally data-only and do not change normal player teleport rules.
 */
class DevHubTeleports(private val objTypes: ObjTypeList) {
    private val spellbooks: List<DevHubTeleportGroup> by lazy { buildSpellbooks() }
    private val serverCatalog: List<SharedTeleport> by lazy { buildServerCatalog() }

    /**
     * The jewellery/item destinations as one `"Group: Destination"` list (~28 entries, safely under
     * the menu's 127-choice cap) - a single category row shared by all teleport items.
     */
    private val itemsFlattened: List<DevHubTeleport> by lazy {
        ITEM_TELEPORTS.flatMap { group ->
                group.teleports.map { DevHubTeleport("${group.label}: ${it.label}", it.coords) }
            }
            .distinctBy { it.coords }
    }

    /** Destinations behind a Teleports-tab category row; null for any other category. */
    fun forCategory(category: DevHubCategory): List<DevHubTeleport>? =
        when (category) {
            DevHubCategory.StandardSpellbook -> spellbooks[0].teleports
            DevHubCategory.AncientSpellbook -> spellbooks[1].teleports
            DevHubCategory.LunarSpellbook -> spellbooks[2].teleports
            DevHubCategory.ArceuusSpellbook -> spellbooks[3].teleports
            DevHubCategory.Cities -> merged(CITIES, sharedGroups("Cities"))
            DevHubCategory.Bosses -> merged(BOSSES, sharedGroups("Bosses"))
            DevHubCategory.Monsters ->
                merged(MONSTERS, sharedCategories("Monsters", excludedGroups = setOf("Bosses")))
            DevHubCategory.Minigames -> merged(MINIGAMES, sharedCategories("Minigames"))
            DevHubCategory.Raids ->
                merged(
                    RAIDS,
                    serverCatalog
                        .filter {
                            val text =
                                "${it.category} ${it.group} ${it.destination.name}".lowercase()
                            "raid" in text ||
                                "theatre" in text ||
                                "tombs" in text ||
                                "chambers" in text
                        }
                        .map { it.toDevHubTeleport() },
                )
            DevHubCategory.Dungeons ->
                merged(
                    DUNGEONS,
                    serverCatalog
                        .filter {
                            val text = "${it.group} ${it.destination.name}".lowercase()
                            "dungeon" in text ||
                                "cave" in text ||
                                "cavern" in text ||
                                "lair" in text ||
                                "tunnel" in text ||
                                "catacomb" in text
                        }
                        .map { it.toDevHubTeleport() },
                )
            DevHubCategory.Wilderness -> merged(WILDERNESS, sharedCategories("Wilderness"))
            DevHubCategory.OtherTeleports ->
                merged(itemsFlattened + OTHER, sharedGroups("Guilds", "Skilling"))
            else -> null
        }

    private fun buildServerCatalog(): List<SharedTeleport> =
        UnforgeTeleports.catalogs().flatMap { (book, categories) ->
            categories.flatMap { category ->
                category.groups.flatMap { group ->
                    group.dests.map { destination ->
                        SharedTeleport(book, category.name, group.name, destination)
                    }
                }
            }
        }

    private fun sharedGroups(vararg names: String): List<DevHubTeleport> {
        val wanted = names.toSet()
        return serverCatalog.filter { it.group in wanted }.map { it.toDevHubTeleport() }
    }

    private fun sharedCategories(
        vararg names: String,
        excludedGroups: Set<String> = emptySet(),
    ): List<DevHubTeleport> {
        val wanted = names.toSet()
        return serverCatalog
            .filter { it.category in wanted && it.group !in excludedGroups }
            .map { it.toDevHubTeleport() }
    }

    private fun merged(
        fallback: List<DevHubTeleport>,
        server: List<DevHubTeleport>,
    ): List<DevHubTeleport> =
        // A destination is identified by its actual tile, not its display label. The same place
        // is often exposed by several spellbooks/items with slightly different names.
        (server + fallback).distinctBy { it.coords }

    private data class SharedTeleport(
        val book: String,
        val category: String,
        val group: String,
        val destination: TeleDest,
    ) {
        fun toDevHubTeleport(): DevHubTeleport =
            DevHubTeleport("$book · $category · $group: ${destination.name}", destination.dest)
    }

    private fun buildSpellbooks(): List<DevHubTeleportGroup> {
        val byBook = mutableMapOf<Int, MutableList<Pair<Int, DevHubTeleport>>>()
        for (type in objTypes.values) {
            val coords = type.paramOrNull(params.spell_telecoord) ?: continue
            val label = type.paramOrNull(params.spell_name) ?: type.name
            val level = type.paramOrNull(params.spell_levelreq) ?: 0
            val book = type.paramOrNull(params.spell_spellbook) ?: 0
            byBook.getOrPut(book) { mutableListOf() } += level to DevHubTeleport(label, coords)
        }
        return SPELLBOOKS.map { (book, name, home) ->
            val spells =
                byBook[book]
                    .orEmpty()
                    .sortedBy { it.first }
                    .map { it.second }
                    .distinctBy { it.coords }
            DevHubTeleportGroup(name, (listOf(home) + spells).distinctBy { it.coords })
        }
    }

    private companion object {
        /** `(spellbook param value, menu label, hand-entered home teleport)` */
        private val SPELLBOOKS =
            listOf(
                Triple(
                    0,
                    "Standard spellbook",
                    DevHubTeleport("Lumbridge Home Teleport", CoordGrid(x = 3222, z = 3218)),
                ),
                Triple(
                    1,
                    "Ancient spellbook",
                    DevHubTeleport("Edgeville Home Teleport", CoordGrid(x = 3087, z = 3496)),
                ),
                Triple(
                    2,
                    "Lunar spellbook",
                    DevHubTeleport("Lunar Home Teleport", CoordGrid(x = 2100, z = 3914)),
                ),
                Triple(
                    3,
                    "Arceuus spellbook",
                    DevHubTeleport("Arceuus Home Teleport", CoordGrid(x = 1712, z = 3882)),
                ),
            )

        private val ITEM_TELEPORTS =
            listOf(
                DevHubTeleportGroup(
                    "Amulet of glory",
                    listOf(
                        DevHubTeleport("Edgeville", CoordGrid(x = 3087, z = 3496)),
                        DevHubTeleport("Karamja", CoordGrid(x = 2918, z = 3176)),
                        DevHubTeleport("Draynor Village", CoordGrid(x = 3105, z = 3251)),
                        DevHubTeleport("Al Kharid", CoordGrid(x = 3293, z = 3163)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Games necklace",
                    listOf(
                        DevHubTeleport("Burthorpe", CoordGrid(x = 2898, z = 3553)),
                        DevHubTeleport("Barbarian Outpost", CoordGrid(x = 2520, z = 3571)),
                        DevHubTeleport("Corporeal Beast", CoordGrid(x = 2966, z = 4382, level = 2)),
                        DevHubTeleport("Wintertodt Camp", CoordGrid(x = 1624, z = 3938)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Ring of dueling",
                    listOf(
                        DevHubTeleport("Emir's Arena", CoordGrid(x = 3316, z = 3235)),
                        DevHubTeleport("Ferox Enclave", CoordGrid(x = 3151, z = 3635)),
                        DevHubTeleport("Castle Wars", CoordGrid(x = 2440, z = 3089)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Ring of wealth",
                    listOf(
                        DevHubTeleport("Grand Exchange", CoordGrid(x = 3164, z = 3487)),
                        DevHubTeleport("Falador Park", CoordGrid(x = 2995, z = 3375)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Combat bracelet",
                    listOf(
                        DevHubTeleport("Warriors' Guild", CoordGrid(x = 2882, z = 3548)),
                        DevHubTeleport("Champions' Guild", CoordGrid(x = 3191, z = 3363)),
                        DevHubTeleport("Monastery", CoordGrid(x = 3052, z = 3488)),
                        DevHubTeleport("Ranging Guild", CoordGrid(x = 2655, z = 3441)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Skills necklace",
                    listOf(
                        DevHubTeleport("Fishing Guild", CoordGrid(x = 2611, z = 3390)),
                        DevHubTeleport("Mining Guild", CoordGrid(x = 3050, z = 9763)),
                        DevHubTeleport("Crafting Guild", CoordGrid(x = 2933, z = 3295)),
                        DevHubTeleport("Cooks' Guild", CoordGrid(x = 3143, z = 3442)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Xeric's talisman",
                    listOf(
                        DevHubTeleport("Xeric's Lookout", CoordGrid(x = 1576, z = 3530)),
                        DevHubTeleport("Xeric's Glade", CoordGrid(x = 1752, z = 3566)),
                        DevHubTeleport("Xeric's Heart", CoordGrid(x = 1504, z = 3817)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Digsite pendant",
                    listOf(
                        DevHubTeleport("Digsite", CoordGrid(x = 3346, z = 3445)),
                        DevHubTeleport("Fossil Island", CoordGrid(x = 3764, z = 3869)),
                    ),
                ),
                DevHubTeleportGroup(
                    "Other items",
                    listOf(
                        DevHubTeleport("Ectofuntus (Ectophial)", CoordGrid(x = 3659, z = 3524)),
                        DevHubTeleport("Grand Tree (Royal seed pod)", CoordGrid(x = 2465, z = 3495)),
                    ),
                ),
            )

        private val CITIES =
            listOf(
                DevHubTeleport("Lumbridge", CoordGrid(x = 3222, z = 3218)),
                DevHubTeleport("Varrock", CoordGrid(x = 3210, z = 3424)),
                DevHubTeleport("Falador", CoordGrid(x = 2965, z = 3379)),
                DevHubTeleport("Edgeville", CoordGrid(x = 3087, z = 3496)),
                DevHubTeleport("Draynor Village", CoordGrid(x = 3105, z = 3251)),
                DevHubTeleport("Al Kharid", CoordGrid(x = 3293, z = 3163)),
                DevHubTeleport("Port Sarim", CoordGrid(x = 3014, z = 3219)),
                DevHubTeleport("Rimmington", CoordGrid(x = 2954, z = 3224)),
                DevHubTeleport("Ardougne", CoordGrid(x = 2662, z = 3305)),
                DevHubTeleport("Camelot", CoordGrid(x = 2757, z = 3477)),
                DevHubTeleport("Seers' Village", CoordGrid(x = 2726, z = 3485)),
                DevHubTeleport("Yanille", CoordGrid(x = 2544, z = 3090)),
                DevHubTeleport("Karamja", CoordGrid(x = 2918, z = 3176)),
                DevHubTeleport("Canifis", CoordGrid(x = 3494, z = 3488)),
                DevHubTeleport("Prifddinas", CoordGrid(x = 3274, z = 6057)),
            )

        private val BOSSES =
            listOf(
                DevHubTeleport("Vorkath", CoordGrid(x = 2272, z = 4050)),
                DevHubTeleport("Zulrah", CoordGrid(x = 2203, z = 3056)),
                DevHubTeleport("Corporeal Beast", CoordGrid(x = 2966, z = 4382, level = 2)),
                DevHubTeleport("God Wars Dungeon", CoordGrid(x = 2878, z = 5310)),
                DevHubTeleport("Barrows", CoordGrid(x = 3565, z = 3313)),
                DevHubTeleport("Kraken", CoordGrid(x = 2280, z = 10016)),
                DevHubTeleport("Cerberus", CoordGrid(x = 1240, z = 12285)),
                DevHubTeleport("Alchemical Hydra", CoordGrid(x = 1355, z = 10260)),
                DevHubTeleport("The Nightmare", CoordGrid(x = 3808, z = 9758)),
                DevHubTeleport("Giant Mole", CoordGrid(x = 1762, z = 5180)),
                DevHubTeleport("King Black Dragon", CoordGrid(x = 3007, z = 3849)),
                DevHubTeleport("Dagannoth Kings", CoordGrid(x = 2900, z = 4449)),
            )

        private val MONSTERS =
            listOf(
                DevHubTeleport("Slayer Tower", CoordGrid(x = 3428, z = 3537)),
                DevHubTeleport("Catacombs of Kourend", CoordGrid(x = 1665, z = 10050)),
                DevHubTeleport("Stronghold Slayer Cave", CoordGrid(x = 2438, z = 3423)),
                DevHubTeleport("Fremennik Slayer Dungeon", CoordGrid(x = 2805, z = 10001)),
                DevHubTeleport("Taverley Dungeon", CoordGrid(x = 2884, z = 9797)),
                DevHubTeleport("Brimhaven Dungeon", CoordGrid(x = 2713, z = 9564)),
                DevHubTeleport("Smoke Devil Dungeon", CoordGrid(x = 3203, z = 9379)),
                DevHubTeleport("Kalphite Lair", CoordGrid(x = 3508, z = 9493)),
                DevHubTeleport("Fossil Island Wyvern Cave", CoordGrid(x = 3616, z = 10288)),
                DevHubTeleport("TzHaar", CoordGrid(x = 2445, z = 5177)),
            )

        private val MINIGAMES =
            listOf(
                DevHubTeleport("Pest Control", CoordGrid(x = 2658, z = 2676)),
                DevHubTeleport("Castle Wars", CoordGrid(x = 2440, z = 3089)),
                DevHubTeleport("Wintertodt Camp", CoordGrid(x = 1624, z = 3938)),
                DevHubTeleport("Tempoross", CoordGrid(x = 3138, z = 2843)),
                DevHubTeleport("Guardians of the Rift", CoordGrid(x = 3039, z = 4822)),
                DevHubTeleport("Nightmare Zone", CoordGrid(x = 2600, z = 3110)),
                DevHubTeleport("Last Man Standing", CoordGrid(x = 3142, z = 3638)),
                DevHubTeleport("Soul Wars", CoordGrid(x = 2215, z = 2850)),
                DevHubTeleport("Mage Training Arena", CoordGrid(x = 3360, z = 3300)),
                DevHubTeleport("TzHaar Fight Cave", CoordGrid(x = 2445, z = 5177)),
            )

        private val RAIDS =
            listOf(
                // 1235,3555 is an empty edge tile. Use the actual CoX lobby/entrance used by
                // the Xeric's talisman and raid teleport definitions.
                DevHubTeleport("Chambers of Xeric", CoordGrid(x = 1254, z = 3558)),
                DevHubTeleport("Theatre of Blood", CoordGrid(x = 3677, z = 3219)),
                DevHubTeleport("Tombs of Amascut", CoordGrid(x = 3368, z = 2795)),
            )

        private val DUNGEONS =
            listOf(
                DevHubTeleport("Taverley Dungeon", CoordGrid(x = 2884, z = 9797)),
                DevHubTeleport("Edgeville Dungeon", CoordGrid(x = 3134, z = 9870)),
                DevHubTeleport("Karamja Dungeon", CoordGrid(x = 2844, z = 9570)),
                DevHubTeleport("Lumbridge Swamp Dungeon", CoordGrid(x = 3168, z = 9571)),
                DevHubTeleport("Waterbirth Island Dungeon", CoordGrid(x = 2446, z = 10147)),
                DevHubTeleport("Smoke Dungeon", CoordGrid(x = 3203, z = 9379)),
                DevHubTeleport("Kourend Catacombs", CoordGrid(x = 1665, z = 10050)),
            )

        private val WILDERNESS =
            listOf(
                DevHubTeleport("Ferox Enclave", CoordGrid(x = 3151, z = 3635)),
                DevHubTeleport("Wilderness Slayer Cave", CoordGrid(x = 3185, z = 10056)),
                DevHubTeleport("Revenant Caves", CoordGrid(x = 3120, z = 10180)),
                DevHubTeleport("Callisto", CoordGrid(x = 3290, z = 3832)),
                DevHubTeleport("Venenatis", CoordGrid(x = 3348, z = 3749)),
                DevHubTeleport("Vet'ion", CoordGrid(x = 3227, z = 3792)),
                DevHubTeleport("Scorpia", CoordGrid(x = 3235, z = 3945)),
                DevHubTeleport("Chaos Temple", CoordGrid(x = 3236, z = 3637)),
                DevHubTeleport("Mage Arena", CoordGrid(x = 3105, z = 3933)),
            )

        private val OTHER =
            listOf(
                DevHubTeleport("Gnome Agility Course", CoordGrid(x = 2474, z = 3436)),
                DevHubTeleport("Ardougne Market", CoordGrid(x = 2662, z = 3305)),
                DevHubTeleport("Rimmington POH Portal", CoordGrid(x = 2954, z = 3224)),
                DevHubTeleport("Grand Exchange", CoordGrid(x = 3164, z = 3487)),
                DevHubTeleport("Slayer Hub", CoordGrid(x = 3428, z = 3537)),
            )
    }
}
