package org.rsmod.content.areas.unforge.map

import org.rsmod.api.type.builders.map.loc.MapLocSpawnBuilder
import org.rsmod.content.areas.unforge.UnforgeScript

object UnforgeLocSpawns : MapLocSpawnBuilder() {
    override fun onPackMapTask() {
        // Binary loc spawn files l<regionX>_<regionZ>, generated by
        // work/port-tools/port_objects.py. Regenerate rather than hand-edit.
        resourceFile<UnforgeScript>("map/l31_87")
        resourceFile<UnforgeScript>("map/l38_55")
        resourceFile<UnforgeScript>("map/l48_60")
        resourceFile<UnforgeScript>("map/l59_44")
    }
}
