package org.rsmod.content.generic.locs.banks

import org.rsmod.api.config.refs.content
import org.rsmod.api.type.editors.loc.LocEditor
import org.rsmod.api.type.refs.loc.LocReferences

// Generated by work/port-tools/gen_bank_edits.py — regenerate, do not hand-edit.
// Every r239 loc exposing a Bank/Use/Deposit option gets its content group,
// so bank functionality works on all spawned bank objects, not only Lumbridge.
internal object BankLocAllRefs : LocReferences() {
    val dwarf_keldagrim_bankbooth = find("dwarf_keldagrim_bankbooth")
    val bankbooth_end_right = find("bankbooth_end_right")
    val bankbooth_end_left = find("bankbooth_end_left")
    val bankbooth = find("bankbooth")
    val bankbooth_deadman = find("bankbooth_deadman")
    val elid_bankbooth = find("elid_bankbooth")
    val fai_varrock_bankbooth = find("fai_varrock_bankbooth")
    val fai_varrock_bankbooth_deadman = find("fai_varrock_bankbooth_deadman")
    val fever_bankbooth = find("fever_bankbooth")
    val pest_bankbooth = find("pest_bankbooth")
    val ahoy_bankbooth = find("ahoy_bankbooth")
    val lunar_moonclan_bankbooth = find("lunar_moonclan_bankbooth")
    val aide_bankbooth = find("aide_bankbooth")
    val elf_village_bankcounter = find("elf_village_bankcounter")
    val contact_bank_booth = find("contact_bank_booth")
    val dorgesh_bank_booth = find("dorgesh_bank_booth")
    val fai_falador_bankbooth = find("fai_falador_bankbooth")
    val canafis_bankbooth = find("canafis_bankbooth")
    val kr_bankbooth = find("kr_bankbooth")
    val fai_falador_bankbooth_deadman = find("fai_falador_bankbooth_deadman")
    val pest_bankbooth_deadman = find("pest_bankbooth_deadman")
    val contact_bank_booth_deadman = find("contact_bank_booth_deadman")
    val kr_bankbooth_deadman = find("kr_bankbooth_deadman")
    val ahoy_bankbooth_deadman = find("ahoy_bankbooth_deadman")
    val aide_bankbooth_deadman = find("aide_bankbooth_deadman")
    val piscarilius_bank_booth_01 = find("piscarilius_bank_booth_01")
    val piscarilius_bank_booth_02 = find("piscarilius_bank_booth_02")
    val piscarilius_bank_booth_03 = find("piscarilius_bank_booth_03")
    val piscarilius_bank_booth_04 = find("piscarilius_bank_booth_04")
    val archeeus_bank_booth_open_01 = find("archeeus_bank_booth_open_01")
    val archeeus_bank_booth_open_02 = find("archeeus_bank_booth_open_02")
    val archeeus_bank_booth_open_03 = find("archeeus_bank_booth_open_03")
    val archeeus_bank_booth_open_04 = find("archeeus_bank_booth_open_04")
    val lova_bank_booth_01 = find("lova_bank_booth_01")
    val lova_bank_booth_02 = find("lova_bank_booth_02")
    val lova_bank_booth_03 = find("lova_bank_booth_03")
    val lova_bank_booth_04 = find("lova_bank_booth_04")
    val banktable_breakroute_bankable = find("banktable_breakroute_bankable")
    val tob_surface_bankbooth = find("tob_surface_bankbooth")
    val prif_bankbooth_open = find("prif_bankbooth_open")
    val darkm_bankbooth = find("darkm_bankbooth")
    val gim_island_bankbooth = find("gim_island_bankbooth")
    val bankbooth_ap1 = find("bankbooth_ap1")
    val cam_torum_bank_table = find("cam_torum_bank_table")
    val cam_torum_bank_table02 = find("cam_torum_bank_table02")
    val table_bank01_civitas01 = find("table_bank01_civitas01")
    val table_bank01_civitas02 = find("table_bank01_civitas02")
    val booth_bank01_talkasti01 = find("booth_bank01_talkasti01")
    val cw_bankbooth_57892 = find("cw_bankbooth_57892")
    val cw_bankboat_60434 = find("cw_bankboat_60434")
    val thbankchest = find("thbankchest")
    val castlewars_bankchest = find("castlewars_bankchest")
    val newbiebankbooth = find("newbiebankbooth")
    val champions_bankchest = find("champions_bankchest")
    val burgh_bankbooth_repaired = find("burgh_bankbooth_repaired")
    val diary_guild_bankchest = find("diary_guild_bankchest")
    val barbassault_bank_chest = find("barbassault_bank_chest")
    val fris_bank_chest_open = find("fris_bank_chest_open")
    val blast_bank_chest = find("blast_bank_chest")
    val fairy_chest_bank = find("fairy_chest_bank")
    val lovakengj_bank_chest_orange = find("lovakengj_bank_chest_orange")
    val lovakengj_bank_chest_grey = find("lovakengj_bank_chest_grey")
    val mm_desk_bankchest = find("mm_desk_bankchest")
    val wcguild_bankchest = find("wcguild_bankchest")
    val wint_bankchest = find("wint_bankchest")
    val tox_bank_chest = find("tox_bank_chest")
    val tzhaar_bank_chest = find("tzhaar_bank_chest")
    val fossil_washed_up_chest = find("fossil_washed_up_chest")
    val fossil_bank_chest_built = find("fossil_bank_chest_built")
    val fossil_volcano_bank_chest = find("fossil_volcano_bank_chest")
    val deadman_arena_bank_chest = find("deadman_arena_bank_chest")
    val brimstone_bankchest = find("brimstone_bankchest")
    val tut2_bankbooth = find("tut2_bankbooth")
    val soul_wars_bankchest = find("soul_wars_bankchest")
    val tempoross_lobby_bank_chest = find("tempoross_lobby_bank_chest")
    val bim_ruins_bankchest = find("bim_ruins_bankchest")
    val gotr_bankchest = find("gotr_bankchest")
    val giants_foundry_chest = find("giants_foundry_chest")
    val toa_bank_camel = find("toa_bank_camel")
    val bh_bankchest = find("bh_bankchest")
    val raids_bank_chest_lobby_working = find("raids_bank_chest_lobby_working")
    val colosseum_bank = find("colosseum_bank")
    val fortis_bank_chest = find("fortis_bank_chest")
    val fortis_bank_chest_small = find("fortis_bank_chest_small")
    val magictraining_bankchest = find("magictraining_bankchest")
    val chest_alchemist01_open01 = find("chest_alchemist01_open01")
    val chest_alchemist01_closed01 = find("chest_alchemist01_closed01")
    val bank_buffalo = find("bank_buffalo")
    val cw_bankchest_57958 = find("cw_bankchest_57958")
    val cw_bankcrab_58094 = find("cw_bankcrab_58094")
    val cw_bankchest_58128 = find("cw_bankchest_58128")
    val cw_bankchest_58129 = find("cw_bankchest_58129")
    val cw_bankchest_58663 = find("cw_bankchest_58663")
    val cw_bankcrab_60435 = find("cw_bankcrab_60435")
    val cw_bankchest_62187 = find("cw_bankchest_62187")
    val bank_deposit_box = find("bank_deposit_box")
    val bank_deposit_chest = find("bank_deposit_chest")
    val kr_bank_deposit_box = find("kr_bank_deposit_box")
    val sarim_deposit_box = find("sarim_deposit_box")
    val diary_guild_deposit_box = find("diary_guild_deposit_box")
    val swan_bank_deposit_box = find("swan_bank_deposit_box")
    val burgh_bank_deposit_box = find("burgh_bank_deposit_box")
    val ahoy_bank_deposit_box = find("ahoy_bank_deposit_box")
    val mm_active_deposit_box = find("mm_active_deposit_box")
    val wint_deposit_box = find("wint_deposit_box")
    val tzhaar_deposit_box = find("tzhaar_deposit_box")
    val corscurs_bank_deposit_box = find("corscurs_bank_deposit_box")
    val tob_surface_deposit_box = find("tob_surface_deposit_box")
    val brimstone_depositbox = find("brimstone_depositbox")
    val gauntlet_deposit_box = find("gauntlet_deposit_box")
    val darkm_deposit_box = find("darkm_deposit_box")
    val clan_medieval_deposit_box = find("clan_medieval_deposit_box")
    val bank_deposit_box_2 = find("bank_deposit_box_2")
    val storage_postbox01_talkasti01 = find("storage_postbox01_talkasti01")
    val cw_bankdepositbox_57996 = find("cw_bankdepositbox_57996")
}

internal object BankAllLocEditor : LocEditor() {
    init {
        // op2=Bank booths/counters/boats (collect op3, deposit-box op4)
        edit(BankLocAllRefs.dwarf_keldagrim_bankbooth) {
            contentGroup = content.bank_booth
        } // 6084 Bank booth
        edit(BankLocAllRefs.bankbooth_end_right) {
            contentGroup = content.bank_booth
        } // 8139 Bank booth
        edit(BankLocAllRefs.bankbooth_end_left) {
            contentGroup = content.bank_booth
        } // 8140 Bank booth
        edit(BankLocAllRefs.bankbooth) { contentGroup = content.bank_booth } // 10355 Bank booth
        edit(BankLocAllRefs.bankbooth_deadman) {
            contentGroup = content.bank_booth
        } // 10357 Bank booth
        edit(BankLocAllRefs.elid_bankbooth) {
            contentGroup = content.bank_booth
        } // 10517 Bank booth
        edit(BankLocAllRefs.fai_varrock_bankbooth) {
            contentGroup = content.bank_booth
        } // 10583 Bank booth
        edit(BankLocAllRefs.fai_varrock_bankbooth_deadman) {
            contentGroup = content.bank_booth
        } // 10584 Bank booth
        edit(BankLocAllRefs.fever_bankbooth) {
            contentGroup = content.bank_booth
        } // 11338 Bank booth
        edit(BankLocAllRefs.pest_bankbooth) {
            contentGroup = content.bank_booth
        } // 14367 Bank booth
        edit(BankLocAllRefs.ahoy_bankbooth) {
            contentGroup = content.bank_booth
        } // 16642 Bank booth
        edit(BankLocAllRefs.lunar_moonclan_bankbooth) {
            contentGroup = content.bank_booth
        } // 16700 Bank booth
        edit(BankLocAllRefs.aide_bankbooth) {
            contentGroup = content.bank_booth
        } // 18491 Bank booth
        edit(BankLocAllRefs.elf_village_bankcounter) {
            contentGroup = content.bank_booth
        } // 20127 Bank counter
        edit(BankLocAllRefs.contact_bank_booth) {
            contentGroup = content.bank_booth
        } // 20325 Bank booth
        edit(BankLocAllRefs.dorgesh_bank_booth) {
            contentGroup = content.bank_booth
        } // 22819 Bank booth
        edit(BankLocAllRefs.fai_falador_bankbooth) {
            contentGroup = content.bank_booth
        } // 24101 Bank booth
        edit(BankLocAllRefs.canafis_bankbooth) {
            contentGroup = content.bank_booth
        } // 24347 Bank booth
        edit(BankLocAllRefs.kr_bankbooth) { contentGroup = content.bank_booth } // 25808 Bank booth
        edit(BankLocAllRefs.fai_falador_bankbooth_deadman) {
            contentGroup = content.bank_booth
        } // 27254 Bank booth
        edit(BankLocAllRefs.pest_bankbooth_deadman) {
            contentGroup = content.bank_booth
        } // 27260 Bank booth
        edit(BankLocAllRefs.contact_bank_booth_deadman) {
            contentGroup = content.bank_booth
        } // 27263 Bank booth
        edit(BankLocAllRefs.kr_bankbooth_deadman) {
            contentGroup = content.bank_booth
        } // 27265 Bank booth
        edit(BankLocAllRefs.ahoy_bankbooth_deadman) {
            contentGroup = content.bank_booth
        } // 27267 Bank booth
        edit(BankLocAllRefs.aide_bankbooth_deadman) {
            contentGroup = content.bank_booth
        } // 27292 Bank booth
        edit(BankLocAllRefs.piscarilius_bank_booth_01) {
            contentGroup = content.bank_booth
        } // 27718 Bank booth
        edit(BankLocAllRefs.piscarilius_bank_booth_02) {
            contentGroup = content.bank_booth
        } // 27719 Bank booth
        edit(BankLocAllRefs.piscarilius_bank_booth_03) {
            contentGroup = content.bank_booth
        } // 27720 Bank booth
        edit(BankLocAllRefs.piscarilius_bank_booth_04) {
            contentGroup = content.bank_booth
        } // 27721 Bank booth
        edit(BankLocAllRefs.archeeus_bank_booth_open_01) {
            contentGroup = content.bank_booth
        } // 28430 Bank booth
        edit(BankLocAllRefs.archeeus_bank_booth_open_02) {
            contentGroup = content.bank_booth
        } // 28431 Bank booth
        edit(BankLocAllRefs.archeeus_bank_booth_open_03) {
            contentGroup = content.bank_booth
        } // 28432 Bank booth
        edit(BankLocAllRefs.archeeus_bank_booth_open_04) {
            contentGroup = content.bank_booth
        } // 28433 Bank booth
        edit(BankLocAllRefs.lova_bank_booth_01) {
            contentGroup = content.bank_booth
        } // 28546 Bank booth
        edit(BankLocAllRefs.lova_bank_booth_02) {
            contentGroup = content.bank_booth
        } // 28547 Bank booth
        edit(BankLocAllRefs.lova_bank_booth_03) {
            contentGroup = content.bank_booth
        } // 28548 Bank booth
        edit(BankLocAllRefs.lova_bank_booth_04) {
            contentGroup = content.bank_booth
        } // 28549 Bank booth
        edit(BankLocAllRefs.banktable_breakroute_bankable) {
            contentGroup = content.bank_booth
        } // 31582 Bank counter
        edit(BankLocAllRefs.tob_surface_bankbooth) {
            contentGroup = content.bank_booth
        } // 32666 Bank booth
        edit(BankLocAllRefs.prif_bankbooth_open) {
            contentGroup = content.bank_booth
        } // 36559 Bank booth
        edit(BankLocAllRefs.darkm_bankbooth) {
            contentGroup = content.bank_booth
        } // 39238 Bank booth
        edit(BankLocAllRefs.gim_island_bankbooth) {
            contentGroup = content.bank_booth
        } // 42837 Bank booth
        edit(BankLocAllRefs.bankbooth_ap1) { contentGroup = content.bank_booth } // 50901 Bank booth
        edit(BankLocAllRefs.cam_torum_bank_table) {
            contentGroup = content.bank_booth
        } // 51515 Bank table
        edit(BankLocAllRefs.cam_torum_bank_table02) {
            contentGroup = content.bank_booth
        } // 51516 Bank table
        edit(BankLocAllRefs.table_bank01_civitas01) {
            contentGroup = content.bank_booth
        } // 52396 Bank table
        edit(BankLocAllRefs.table_bank01_civitas02) {
            contentGroup = content.bank_booth
        } // 52397 Bank table
        edit(BankLocAllRefs.booth_bank01_talkasti01) {
            contentGroup = content.bank_booth
        } // 57330 Bank booth
        edit(BankLocAllRefs.cw_bankbooth_57892) {
            contentGroup = content.bank_booth
        } // 57892 Bank booth
        edit(BankLocAllRefs.cw_bankboat_60434) {
            contentGroup = content.bank_booth
        } // 60434 Bank boat
        // op1=Bank|Use chests and misc bank objects (collect op3)
        edit(BankLocAllRefs.thbankchest) { contentGroup = content.bank_chest } // 2693 Bank chest
        edit(BankLocAllRefs.castlewars_bankchest) {
            contentGroup = content.bank_chest
        } // 4483 Bank chest
        edit(BankLocAllRefs.newbiebankbooth) {
            contentGroup = content.bank_chest
        } // 10083 Bank booth
        edit(BankLocAllRefs.champions_bankchest) {
            contentGroup = content.bank_chest
        } // 10562 Bank chest
        edit(BankLocAllRefs.burgh_bankbooth_repaired) {
            contentGroup = content.bank_chest
        } // 12798 Bank Booth
        edit(BankLocAllRefs.diary_guild_bankchest) {
            contentGroup = content.bank_chest
        } // 14886 Bank chest
        edit(BankLocAllRefs.barbassault_bank_chest) {
            contentGroup = content.bank_chest
        } // 19051 Bank chest
        edit(BankLocAllRefs.fris_bank_chest_open) {
            contentGroup = content.bank_chest
        } // 21301 Bank chest
        edit(BankLocAllRefs.blast_bank_chest) {
            contentGroup = content.bank_chest
        } // 26707 Bank chest
        edit(BankLocAllRefs.fairy_chest_bank) {
            contentGroup = content.bank_chest
        } // 26711 Bank chest
        edit(BankLocAllRefs.lovakengj_bank_chest_orange) {
            contentGroup = content.bank_chest
        } // 28594 Bank chest
        edit(BankLocAllRefs.lovakengj_bank_chest_grey) {
            contentGroup = content.bank_chest
        } // 28595 Bank chest
        edit(BankLocAllRefs.mm_desk_bankchest) {
            contentGroup = content.bank_chest
        } // 28816 Bank chest
        edit(BankLocAllRefs.wcguild_bankchest) {
            contentGroup = content.bank_chest
        } // 28861 Bank chest
        edit(BankLocAllRefs.wint_bankchest) {
            contentGroup = content.bank_chest
        } // 29321 Bank chest
        edit(BankLocAllRefs.tox_bank_chest) {
            contentGroup = content.bank_chest
        } // 30087 Bank chest
        edit(BankLocAllRefs.tzhaar_bank_chest) {
            contentGroup = content.bank_chest
        } // 30267 Bank chest
        edit(BankLocAllRefs.fossil_washed_up_chest) {
            contentGroup = content.bank_chest
        } // 30796 Bank Chest
        edit(BankLocAllRefs.fossil_bank_chest_built) {
            contentGroup = content.bank_chest
        } // 30926 Bank chest
        edit(BankLocAllRefs.fossil_volcano_bank_chest) {
            contentGroup = content.bank_chest
        } // 30989 Bank chest
        edit(BankLocAllRefs.deadman_arena_bank_chest) {
            contentGroup = content.bank_chest
        } // 31949 Bank Box
        edit(BankLocAllRefs.brimstone_bankchest) {
            contentGroup = content.bank_chest
        } // 34343 Bank chest
        edit(BankLocAllRefs.tut2_bankbooth) {
            contentGroup = content.bank_chest
        } // 37959 Bank booth
        edit(BankLocAllRefs.soul_wars_bankchest) {
            contentGroup = content.bank_chest
        } // 40473 Bank chest
        edit(BankLocAllRefs.tempoross_lobby_bank_chest) {
            contentGroup = content.bank_chest
        } // 41315 Bank chest
        edit(BankLocAllRefs.bim_ruins_bankchest) {
            contentGroup = content.bank_chest
        } // 41493 Bank chest
        edit(BankLocAllRefs.gotr_bankchest) {
            contentGroup = content.bank_chest
        } // 43697 Bank Chest
        edit(BankLocAllRefs.giants_foundry_chest) {
            contentGroup = content.bank_chest
        } // 44630 Bank chest
        edit(BankLocAllRefs.toa_bank_camel) {
            contentGroup = content.bank_chest
        } // 46075 <col=ffff00>Bank Camel</col>
        edit(BankLocAllRefs.bh_bankchest) { contentGroup = content.bank_chest } // 47345 Bank chest
        edit(BankLocAllRefs.raids_bank_chest_lobby_working) {
            contentGroup = content.bank_chest
        } // 47420 Bank chest
        edit(BankLocAllRefs.colosseum_bank) {
            contentGroup = content.bank_chest
        } // 50748 Bank chest
        edit(BankLocAllRefs.fortis_bank_chest) {
            contentGroup = content.bank_chest
        } // 53014 Bank chest
        edit(BankLocAllRefs.fortis_bank_chest_small) {
            contentGroup = content.bank_chest
        } // 53015 Bank chest
        edit(BankLocAllRefs.magictraining_bankchest) {
            contentGroup = content.bank_chest
        } // 53260 Bank chest
        edit(BankLocAllRefs.chest_alchemist01_open01) {
            contentGroup = content.bank_chest
        } // 54933 Bank Chest
        edit(BankLocAllRefs.chest_alchemist01_closed01) {
            contentGroup = content.bank_chest
        } // 54934 Bank Chest
        edit(BankLocAllRefs.bank_buffalo) {
            contentGroup = content.bank_chest
        } // 55199 <col=ffff00>Bank buffalo</col>
        edit(BankLocAllRefs.cw_bankchest_57958) {
            contentGroup = content.bank_chest
        } // 57958 Bank chest
        edit(BankLocAllRefs.cw_bankcrab_58094) {
            contentGroup = content.bank_chest
        } // 58094 <col=ffff00>Bank Crab</col>
        edit(BankLocAllRefs.cw_bankchest_58128) {
            contentGroup = content.bank_chest
        } // 58128 Bank chest
        edit(BankLocAllRefs.cw_bankchest_58129) {
            contentGroup = content.bank_chest
        } // 58129 Bank chest
        edit(BankLocAllRefs.cw_bankchest_58663) {
            contentGroup = content.bank_chest
        } // 58663 Bank chest
        edit(BankLocAllRefs.cw_bankcrab_60435) {
            contentGroup = content.bank_chest
        } // 60435 <col=ffff00>Bank Crab</col>
        edit(BankLocAllRefs.cw_bankchest_62187) {
            contentGroup = content.bank_chest
        } // 62187 Bank chest
        // op1=Deposit boxes/chests/pots
        edit(BankLocAllRefs.bank_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 10529 Bank Deposit Box
        edit(BankLocAllRefs.bank_deposit_chest) {
            contentGroup = content.bank_deposit_box
        } // 10530 Bank Deposit Chest
        edit(BankLocAllRefs.kr_bank_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 25937 Bank deposit box
        edit(BankLocAllRefs.sarim_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 26254 Bank deposit box
        edit(BankLocAllRefs.diary_guild_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 29103 Bank Deposit Box
        edit(BankLocAllRefs.swan_bank_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 29104 Bank Deposit Box
        edit(BankLocAllRefs.burgh_bank_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 29105 Bank deposit box
        edit(BankLocAllRefs.ahoy_bank_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 29106 Bank deposit box
        edit(BankLocAllRefs.mm_active_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 29108 Bank Deposit Pot
        edit(BankLocAllRefs.wint_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 29327 Bank Deposit Box
        edit(BankLocAllRefs.tzhaar_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 30268 Bank Deposit Box
        edit(BankLocAllRefs.corscurs_bank_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 31726 Bank deposit box
        edit(BankLocAllRefs.tob_surface_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 32665 Bank Deposit Box
        edit(BankLocAllRefs.brimstone_depositbox) {
            contentGroup = content.bank_deposit_box
        } // 34344 Bank Deposit Box
        edit(BankLocAllRefs.gauntlet_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 36086 Bank Deposit Box
        edit(BankLocAllRefs.darkm_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 39239 Bank Deposit Box
        edit(BankLocAllRefs.clan_medieval_deposit_box) {
            contentGroup = content.bank_deposit_box
        } // 41723 Bank deposit box
        edit(BankLocAllRefs.bank_deposit_box_2) {
            contentGroup = content.bank_deposit_box
        } // 50902 Bank Deposit Box
        edit(BankLocAllRefs.storage_postbox01_talkasti01) {
            contentGroup = content.bank_deposit_box
        } // 57331 Bank Deposit Box
        edit(BankLocAllRefs.cw_bankdepositbox_57996) {
            contentGroup = content.bank_deposit_box
        } // 57996 Bank Deposit Box
    }
}
