package org.rsmod.content.areas.unforge.teleports

import jakarta.inject.Inject
import org.rsmod.api.player.dialogue.Dialogue
import org.rsmod.api.player.protect.ProtectedAccess
import org.rsmod.api.script.onOpNpc1
import org.rsmod.api.type.refs.npc.NpcReferences
import org.rsmod.content.areas.unforge.editor.UnforgeCustomTeles
import org.rsmod.game.entity.Npc
import org.rsmod.map.CoordGrid
import org.rsmod.plugin.scripts.PluginScript
import org.rsmod.plugin.scripts.ScriptContext

// Generated by work/port-tools/port_teleports.py — regenerate, do not hand-edit.

data class TeleDest(val name: String, val dest: CoordGrid)

data class TeleGroup(val name: String, val dests: List<TeleDest>)

data class TeleCat(val name: String, val groups: List<TeleGroup>)

object UnforgePortalNpc : NpcReferences() {
    val portalMage = find("arceuus_darkwizard_reading")
}

class UnforgeTeleports @Inject constructor() : PluginScript() {

    override fun ScriptContext.startup() {
        onOpNpc1(UnforgePortalNpc.portalMage) { openMenu(it.npc) }
    }

    private suspend fun ProtectedAccess.openMenu(npc: Npc) {
        startDialogue(npc) {
            chatNpc(neutral, "Where would you like to go?")
            val custom = UnforgeCustomTeles.asBook()
            val books =
                listOf("Eco" to ECO, "PvP" to PVP, "Test Zones" to TESTZONES) +
                    if (custom.isEmpty()) emptyList() else listOf("Custom" to custom)
            val tree = pick("Select a teleport book", books) ?: return@startDialogue
            val cat = pick("Select a category", tree.map { it.name to it }) ?: return@startDialogue
            val group =
                pick("Select an area", cat.groups.map { it.name to it }) ?: return@startDialogue
            val dest =
                pick("Select a destination", group.dests.map { it.name to it.dest })
                    ?: return@startDialogue
            access.teleport(dest)
        }
    }

    private suspend fun <T> Dialogue.pick(title: String, options: List<Pair<String, T>>): T? {
        var page = 0
        while (true) {
            val slice = options.drop(page * 4).take(4)
            val more = options.size > (page + 1) * 4
            val labels = slice.map { it.first } + if (more) "More..." else "Cancel"
            val idx: Int =
                when (labels.size) {
                    2 -> choice2(labels[0], 0, labels[1], -1, title = title)
                    3 -> choice3(labels[0], 0, labels[1], 1, labels[2], -1, title = title)
                    4 ->
                        choice4(
                            labels[0],
                            0,
                            labels[1],
                            1,
                            labels[2],
                            2,
                            labels[3],
                            -1,
                            title = title,
                        )
                    else ->
                        choice5(
                            labels[0],
                            0,
                            labels[1],
                            1,
                            labels[2],
                            2,
                            labels[3],
                            3,
                            labels[4],
                            -1,
                            title = title,
                        )
                }
            if (idx == -1) {
                if (more) page++ else return null
            } else return options[page * 4 + idx].second
        }
    }

    companion object {
        /**
         * Shared read-only teleport catalog for admin/debug UIs. The gameplay portal keeps using
         * the same data below; exposing it here prevents a second, drifting destination list.
         */
        fun catalogs(): List<Pair<String, List<TeleCat>>> =
            listOf("Eco" to ECO, "PvP" to PVP, "Test Zones" to TESTZONES)

        private val TESTZONES: List<TeleCat> =
            listOf(
                TeleCat(
                    "Combat",
                    listOf(
                        TeleGroup(
                            "Test Zone",
                            listOf(
                                TeleDest(
                                    "Combat Test Zone (basics + bosses)",
                                    CoordGrid(2425, 9531, 0),
                                )
                            ),
                        )
                    ),
                )
            )

        private val ECO: List<TeleCat> =
            listOf(
                TeleCat(
                    "General",
                    listOf(
                        TeleGroup(
                            "Cities",
                            listOf(
                                TeleDest("Al Kharid", CoordGrid(3299, 3197, 0)),
                                TeleDest("Ardougne", CoordGrid(2662, 3307, 0)),
                                TeleDest("Ape Atoll", CoordGrid(2805, 2794, 0)),
                                TeleDest("Barbarian Village", CoordGrid(3085, 3421, 0)),
                                TeleDest("Burthope", CoordGrid(2899, 3544, 0)),
                                TeleDest("Canifis", CoordGrid(3495, 3490, 0)),
                                TeleDest("Catherby", CoordGrid(2804, 3435, 0)),
                                TeleDest("Crash Island", CoordGrid(2894, 2728, 0)),
                                TeleDest("Draynor Village", CoordGrid(3103, 3249, 0)),
                                TeleDest("Falador", CoordGrid(2965, 3379, 0)),
                                TeleDest("Karamja", CoordGrid(2914, 3151, 0)),
                                TeleDest("Lumbridge", CoordGrid(3225, 3219, 0)),
                                TeleDest("Lunar Isle", CoordGrid(2152, 3856, 0)),
                                TeleDest("Miscellania", CoordGrid(2564, 3847, 0)),
                                TeleDest("Port Sarim", CoordGrid(3027, 3241, 0)),
                                TeleDest("Rellekka", CoordGrid(2631, 3676, 0)),
                                TeleDest("Seers' Village", CoordGrid(2710, 3485, 0)),
                                TeleDest("Taverly", CoordGrid(2898, 3454, 0)),
                                TeleDest("TzHaar", CoordGrid(2441, 5170, 0)),
                                TeleDest("Varrock", CoordGrid(3214, 3424, 0)),
                                TeleDest("Yanille", CoordGrid(2605, 3094, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Guilds",
                            listOf(
                                TeleDest("Cooking Guild", CoordGrid(3143, 3442, 0)),
                                TeleDest("Crafting Guild", CoordGrid(2933, 3291, 0)),
                                TeleDest("Fishing Guild", CoordGrid(2611, 3390, 0)),
                                TeleDest("Mining Guild", CoordGrid(3022, 3337, 0)),
                                TeleDest("Woodcutting Guild", CoordGrid(1661, 3505, 0)),
                            ),
                        ),
                    ),
                ),
                TeleCat(
                    "Skilling",
                    listOf(
                        TeleGroup(
                            "Agility",
                            listOf(
                                TeleDest("Gnome Stronghold Course", CoordGrid(2471, 3437, 0)),
                                TeleDest(
                                    "Draynor Village Rooftop Course",
                                    CoordGrid(3105, 3272, 0),
                                ),
                                TeleDest("Al Kharid Rooftop Course", CoordGrid(3281, 3197, 0)),
                                TeleDest("Varrock Rooftop Course", CoordGrid(3224, 3415, 0)),
                                TeleDest("Barbarian Outpost Course", CoordGrid(2552, 3557, 0)),
                                TeleDest("Canifis Rooftop Course", CoordGrid(3505, 3486, 0)),
                                TeleDest("Falador Rooftop Course", CoordGrid(3037, 3339, 0)),
                                TeleDest("Seers' Village Rooftop Course", CoordGrid(2728, 3485, 0)),
                                TeleDest("Rellekka Rooftop Course", CoordGrid(2629, 3677, 0)),
                                TeleDest("Ardougne Rooftop Course", CoordGrid(2673, 3296, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Crafting",
                            listOf(
                                TeleDest("Flax Field", CoordGrid(2741, 3442, 0)),
                                TeleDest("Pottery Oven", CoordGrid(3086, 3409, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Fishing",
                            listOf(
                                TeleDest("Aerial Fishing", CoordGrid(1368, 3633, 0)),
                                TeleDest("Barbarian Village", CoordGrid(3102, 3427, 0)),
                                TeleDest("Catherby Shores", CoordGrid(2809, 3435, 0)),
                                TeleDest("Draynor Shores", CoordGrid(3091, 3225, 0)),
                                TeleDest("Great Kourend Anglers", CoordGrid(1829, 3782, 0)),
                                TeleDest("Karamja Docks", CoordGrid(2925, 3177, 0)),
                                TeleDest("Lumbridge River", CoordGrid(3240, 3251, 0)),
                                TeleDest("Otto's Barbarian Fishing", CoordGrid(2503, 3488, 0)),
                                TeleDest("Piscatoris Fishing Colony", CoordGrid(2341, 3666, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Hunter",
                            listOf(
                                TeleDest("Canifis Swamp (Swamp Lizard)", CoordGrid(3538, 3449, 0)),
                                TeleDest(
                                    "<col=FF4500>(Wilderness) Chinchompa Hill (Black Chinchompa)",
                                    CoordGrid(3145, 3771, 0),
                                ),
                                TeleDest(
                                    "Desert Hunting (Golden Warbler/Orange Salamander)",
                                    CoordGrid(3407, 3073, 0),
                                ),
                                TeleDest("Feldip Hills (Crimson Swift)", CoordGrid(2603, 2932, 0)),
                                TeleDest(
                                    "Gnome-Khazard Battlefield (Red Salamander)",
                                    CoordGrid(2451, 3221, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>(Wilderness) Hill Giants (Black Salamander)",
                                    CoordGrid(3302, 3668, 0),
                                ),
                                TeleDest(
                                    "Jungle Hunting (Tropical Wagtail/Carnviorous Chinchompa)",
                                    CoordGrid(2533, 2921, 0),
                                ),
                                TeleDest(
                                    "Snow Hunting (Cerulean Twitch)",
                                    CoordGrid(2723, 3771, 0),
                                ),
                                TeleDest(
                                    "Woodland Hunting (Copper Longtail/Chinchompa)",
                                    CoordGrid(2341, 3597, 0),
                                ),
                            ),
                        ),
                        TeleGroup(
                            "Mining",
                            listOf(
                                TeleDest("Dwarven Mine", CoordGrid(3043, 9817, 0)),
                                TeleDest("Essence Mine - Dense", CoordGrid(1769, 3849, 0)),
                                TeleDest("Essence Mine - Regular", CoordGrid(2911, 4831, 0)),
                                TeleDest("Gem Mine", CoordGrid(2825, 2997, 0)),
                                TeleDest("Jatizso Mine", CoordGrid(2406, 10190, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Thieving",
                            listOf(
                                TeleDest("Ardougne Marketplace", CoordGrid(2661, 3305, 0)),
                                TeleDest("Draynor Marketplace", CoordGrid(3082, 3250, 0)),
                                TeleDest("Keldagrim Marketplace", CoordGrid(2899, 10199, 0)),
                                TeleDest("Rogues' Den", CoordGrid(3046, 4969, 1)),
                            ),
                        ),
                    ),
                ),
                TeleCat(
                    "Monsters",
                    listOf(
                        TeleGroup(
                            "Beginner",
                            listOf(
                                TeleDest("Cows", CoordGrid(3246, 3274, 0)),
                                TeleDest("Edgeville Dungeon", CoordGrid(3096, 3468, 0)),
                                TeleDest("Experiments", CoordGrid(3574, 9928, 0)),
                                TeleDest("Goblin Village", CoordGrid(2956, 3501, 0)),
                                TeleDest("Lumbridge Swamp Caves", CoordGrid(3168, 9572, 0)),
                                TeleDest("Rock Crabs", CoordGrid(2676, 3711, 0)),
                                TeleDest("Sand Crabs", CoordGrid(1723, 3464, 0)),
                                TeleDest("Stronghold Security", CoordGrid(3081, 3421, 0)),
                                TeleDest("Varrock Sewers", CoordGrid(3237, 3459, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Advanced",
                            listOf(
                                TeleDest("Ancient Cavern", CoordGrid(1762, 5361, 0)),
                                TeleDest("Asganian Ice Dungeon", CoordGrid(3006, 9550, 0)),
                                TeleDest("Bandit Camp", CoordGrid(3170, 2982, 0)),
                                TeleDest("Brimhaven Dungeon", CoordGrid(2710, 9564, 0)),
                                TeleDest("Brine Rat Cavern", CoordGrid(2696, 10121, 0)),
                                TeleDest("Catacombs of Kourend", CoordGrid(1665, 10049, 0)),
                                TeleDest("Chasm of Fire", CoordGrid(1435, 3671, 0)),
                                TeleDest("Crash Site Cavern", CoordGrid(2026, 5610, 0)),
                                TeleDest("Fremennik Slayer Dungeon", CoordGrid(2805, 10001, 0)),
                                TeleDest("Godwars Dungeon", CoordGrid(2916, 3746, 0)),
                                TeleDest("Jungle Demons", CoordGrid(2715, 9211, 1)),
                                TeleDest("Kalphite Lair", CoordGrid(3226, 3108, 0)),
                                TeleDest("Karuulm Slayer Dungeon", CoordGrid(1311, 10188, 0)),
                                TeleDest("Kraken Cove", CoordGrid(2278, 3609, 0)),
                                TeleDest("Mourner Tunnels", CoordGrid(2029, 4636, 0)),
                                TeleDest("Mos Le'Harmless Caves", CoordGrid(3823, 9425, 0)),
                                TeleDest("Slayer Tower", CoordGrid(3428, 3534, 0)),
                                TeleDest("Smoke Dungeon", CoordGrid(3203, 9379, 0)),
                                TeleDest("Smoke Devil Dungeon", CoordGrid(2412, 3060, 0)),
                                TeleDest("Stronghold Slayer Cave", CoordGrid(2431, 3424, 0)),
                                TeleDest("Taverley Dungeon", CoordGrid(2884, 9799, 0)),
                                TeleDest("Trollheim trollpit", CoordGrid(2884, 3588, 0)),
                                TeleDest("Waterbirth Dungeon", CoordGrid(2443, 10146, 0)),
                                TeleDest("Waterfall Dungeon", CoordGrid(2573, 9866, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Bosses",
                            listOf(
                                TeleDest("Abyssal Sire", CoordGrid(3038, 4771, 0)),
                                TeleDest("Adamant & Runite Dragons", CoordGrid(1568, 5075, 0)),
                                TeleDest("Cave Kraken", CoordGrid(2292, 10008, 0)),
                                TeleDest("Cerberus", CoordGrid(1310, 1252, 0)),
                                TeleDest("Corporeal Beast", CoordGrid(2966, 4382, 2)),
                                TeleDest("Dagannoth Kings", CoordGrid(1912, 4367, 0)),
                                TeleDest("Demonic Gorillas", CoordGrid(2026, 5610, 0)),
                                TeleDest("Elvarg", CoordGrid(2844, 9635, 0)),
                                TeleDest("Giant Mole", CoordGrid(1764, 5179, 0)),
                                TeleDest("God Wars", CoordGrid(2916, 3746, 0)),
                                TeleDest("Kalphite Queen", CoordGrid(3509, 9487, 2)),
                                TeleDest("Lizard Shamans (Canyon)", CoordGrid(1445, 3699, 0)),
                                TeleDest("Lizard Shamans (Cavern)", CoordGrid(1309, 3573, 0)),
                                TeleDest("Mithril Dragons", CoordGrid(1777, 5345, 1)),
                                TeleDest("Thermonuclear Smoke Devils", CoordGrid(2412, 3060, 0)),
                                TeleDest("Vorkath", CoordGrid(2272, 4051, 0)),
                                TeleDest("Zulrah", CoordGrid(2198, 3057, 0)),
                            ),
                        ),
                    ),
                ),
                TeleCat(
                    "Minigames",
                    listOf(
                        TeleGroup(
                            "N/A",
                            listOf(
                                TeleDest("Last Man Standing", CoordGrid(3400, 3180, 0)),
                                TeleDest("Barrows", CoordGrid(3565, 3313, 0)),
                                TeleDest("Duel Arena", CoordGrid(3367, 3265, 0)),
                                TeleDest("Fight Caves", CoordGrid(2443, 5171, 0)),
                                TeleDest("Motherlode Mine", CoordGrid(3751, 5669, 0)),
                                TeleDest("Puro Puro", CoordGrid(2426, 4443, 0)),
                                TeleDest("Warriors' Guild", CoordGrid(2880, 3546, 0)),
                                TeleDest("Wintertodt", CoordGrid(1630, 3957, 0)),
                                TeleDest("Raids 1", CoordGrid(1254, 3558, 0)),
                                TeleDest("Pest Control", CoordGrid(2659, 2676, 0)),
                            ),
                        )
                    ),
                ),
                TeleCat(
                    "Wilderness",
                    listOf(
                        TeleGroup(
                            "General",
                            listOf(
                                TeleDest("Mage Bank", CoordGrid(2539, 4717, 0)),
                                TeleDest(
                                    "<col=FF4500>Level 11 - West Dragons",
                                    CoordGrid(2994, 3624, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 15 - Chaos Temple",
                                    CoordGrid(3236, 3638, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 17 - Revenant Cave",
                                    CoordGrid(3069, 3651, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 18 - East Dragons",
                                    CoordGrid(3343, 3663, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 19 - Graveyard of Shadows",
                                    CoordGrid(3149, 3669, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 28 - Forgotten Cemetery",
                                    CoordGrid(2968, 3739, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 47 - Demonic Ruins",
                                    CoordGrid(3286, 3881, 0),
                                ),
                            ),
                        ),
                        TeleGroup(
                            "Obelisks",
                            listOf(
                                TeleDest(
                                    "<col=FF4500>Level 13 - Wilderness Obelisk",
                                    CoordGrid(3144, 3622, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 19 - Wilderness Obelisk",
                                    CoordGrid(3211, 3664, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 35 - Wilderness Obelisk",
                                    CoordGrid(3097, 3799, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 44 - Wilderness Obelisk",
                                    CoordGrid(2979, 3871, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>Level 50 - Wilderness Obelisk",
                                    CoordGrid(3307, 3916, 0),
                                ),
                            ),
                        ),
                        TeleGroup(
                            "Instances",
                            listOf(
                                TeleDest("Camelot", CoordGrid(2758, 3479, 0)),
                                TeleDest("Edgeville", CoordGrid(3096, 3497, 0)),
                                TeleDest("Falador", CoordGrid(2945, 3370, 0)),
                                TeleDest("Lumbridge", CoordGrid(3223, 3219, 0)),
                            ),
                        ),
                    ),
                ),
            )

        private val PVP: List<TeleCat> =
            listOf(
                TeleCat(
                    "General",
                    listOf(
                        TeleGroup(
                            "Cities",
                            listOf(
                                TeleDest("Al Kharid", CoordGrid(3299, 3197, 0)),
                                TeleDest("Ardougne", CoordGrid(2662, 3307, 0)),
                                TeleDest("Ape Atoll", CoordGrid(2805, 2794, 0)),
                                TeleDest("Barbarian Village", CoordGrid(3085, 3421, 0)),
                                TeleDest("Burthope", CoordGrid(2899, 3544, 0)),
                                TeleDest("Canifis", CoordGrid(3495, 3490, 0)),
                                TeleDest("Catherby", CoordGrid(2804, 3435, 0)),
                                TeleDest("Crash Island", CoordGrid(2894, 2728, 0)),
                                TeleDest("Draynor Village", CoordGrid(3103, 3249, 0)),
                                TeleDest("Falador", CoordGrid(2965, 3379, 0)),
                                TeleDest("Karamja", CoordGrid(2914, 3151, 0)),
                                TeleDest("Lumbridge", CoordGrid(3225, 3219, 0)),
                                TeleDest("Lunar Isle", CoordGrid(2152, 3856, 0)),
                                TeleDest("Miscellania", CoordGrid(2564, 3847, 0)),
                                TeleDest("Port Sarim", CoordGrid(3027, 3241, 0)),
                                TeleDest("Rellekka", CoordGrid(2631, 3676, 0)),
                                TeleDest("Seers' Village", CoordGrid(2710, 3485, 0)),
                                TeleDest("Taverly", CoordGrid(2898, 3454, 0)),
                                TeleDest("TzHaar", CoordGrid(2441, 5170, 0)),
                                TeleDest("Varrock", CoordGrid(3214, 3424, 0)),
                                TeleDest("Yanille", CoordGrid(2605, 3094, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Guilds",
                            listOf(
                                TeleDest("Cooking Guild", CoordGrid(3143, 3442, 0)),
                                TeleDest("Crafting Guild", CoordGrid(2933, 3291, 0)),
                                TeleDest("Fishing Guild", CoordGrid(2611, 3390, 0)),
                                TeleDest("Mining Guild", CoordGrid(3022, 3337, 0)),
                                TeleDest("Woodcutting Guild", CoordGrid(1661, 3505, 0)),
                            ),
                        ),
                    ),
                ),
                TeleCat(
                    "Wilderness",
                    listOf(
                        TeleGroup(
                            "General",
                            listOf(
                                TeleDest("Magebank", CoordGrid(2539, 4716, 0)),
                                TeleDest(
                                    "Chaos Temple|<col=FF0000>Level 15|<img=43> <img=46>",
                                    CoordGrid(3236, 3638, 0),
                                ),
                                TeleDest(
                                    "East Dragons|<col=FF0000>Level 19|<img=46>",
                                    CoordGrid(3364, 3666, 0),
                                ),
                                TeleDest(
                                    "West Dragons|<col=FF0000>Level 10|<img=46>",
                                    CoordGrid(2983, 3598, 0),
                                ),
                                TeleDest(
                                    "Demonic Ruins|<col=FF0000>Level 46|<img=43> <img=46>",
                                    CoordGrid(3287, 3886, 0),
                                ),
                                TeleDest(
                                    "Graveyard|<col=FF0000>Level 20|<img=46>",
                                    CoordGrid(3160, 3676, 0),
                                ),
                                TeleDest(
                                    "Revenant Cave|<col=FF0000>Level 17|<img=43> <img=46>",
                                    CoordGrid(3069, 3651, 0),
                                ),
                                TeleDest(
                                    "Revenant Cave|<col=FF0000>Level 40|<img=43> <img=46>",
                                    CoordGrid(3129, 3833, 0),
                                ),
                            ),
                        ),
                        TeleGroup(
                            "Obelisks",
                            listOf(
                                TeleDest(
                                    "Obelisk|<col=FF0000>Level 13|<img=43> <img=46>",
                                    CoordGrid(3144, 3622, 0),
                                ),
                                TeleDest(
                                    "Obelisk|<col=FF0000>Level 19|<img=43> <img=46>",
                                    CoordGrid(3211, 3664, 0),
                                ),
                                TeleDest(
                                    "Obelisk|<col=FF0000>Level 27|<img=46>",
                                    CoordGrid(3041, 3731, 0),
                                ),
                                TeleDest(
                                    "Obelisk|<col=FF0000>Level 35|<img=46>",
                                    CoordGrid(3097, 3799, 0),
                                ),
                                TeleDest(
                                    "Obelisk|<col=FF0000>Level 44|<img=46>",
                                    CoordGrid(2979, 3871, 0),
                                ),
                                TeleDest(
                                    "Obelisk|<col=FF0000>Level 50|<img=46>",
                                    CoordGrid(3307, 3916, 0),
                                ),
                            ),
                        ),
                    ),
                ),
                TeleCat(
                    "Monsters",
                    listOf(
                        TeleGroup(
                            "Paid",
                            listOf(
                                TeleDest(
                                    "Armadyl|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(2839, 5292, 2),
                                ),
                                TeleDest(
                                    "Bandos|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(2858, 5354, 2),
                                ),
                                TeleDest(
                                    "Callisto|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(3295, 3841, 0),
                                ),
                                TeleDest(
                                    "Chaos Elemental|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(3242, 3915, 0),
                                ),
                                TeleDest(
                                    "Chaos Fanatic|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(2984, 3831, 0),
                                ),
                                TeleDest(
                                    "Demonic Gorillas|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(3108, 3676, 0),
                                ),
                                TeleDest(
                                    "Lava Dragons|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(3202, 3859, 0),
                                ),
                                TeleDest(
                                    "Saradomin|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(2910, 5265, 0),
                                ),
                                TeleDest(
                                    "Scorpia|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(3236, 3946, 0),
                                ),
                                TeleDest(
                                    "Venenatis|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(3345, 3728, 0),
                                ),
                                TeleDest(
                                    "Zamorak|<col=FF0000>100 bm|<img=47> <img=46>",
                                    CoordGrid(2925, 5336, 2),
                                ),
                            ),
                        ),
                        TeleGroup(
                            "Beginner",
                            listOf(
                                TeleDest("Cows", CoordGrid(3246, 3274, 0)),
                                TeleDest("Edgeville Dungeon", CoordGrid(3096, 9867, 0)),
                                TeleDest("Experiments", CoordGrid(3574, 9928, 0)),
                                TeleDest("Goblin Village", CoordGrid(2956, 3501, 0)),
                                TeleDest("Lumbridge Swamp Caves", CoordGrid(3168, 9572, 0)),
                                TeleDest("Rock Crabs", CoordGrid(2676, 3711, 0)),
                                TeleDest("Sand Crabs", CoordGrid(1723, 3464, 0)),
                                TeleDest("Stronghold Security", CoordGrid(3081, 3421, 0)),
                                TeleDest("Varrock Sewers", CoordGrid(3237, 3459, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Advanced",
                            listOf(
                                TeleDest("Ancient Cavern", CoordGrid(1762, 5361, 0)),
                                TeleDest("Asganian Ice Dungeon", CoordGrid(3006, 9550, 0)),
                                TeleDest("Bandit Camp", CoordGrid(3170, 2982, 0)),
                                TeleDest("Brimhaven Dungeon", CoordGrid(2710, 9564, 0)),
                                TeleDest("Brine Rat Cavern", CoordGrid(2696, 10121, 0)),
                                TeleDest("Catacombs of Kourend", CoordGrid(1665, 10049, 0)),
                                TeleDest("Chasm of Fire", CoordGrid(1435, 3671, 0)),
                                TeleDest("Crash Site Cavern", CoordGrid(2026, 5610, 0)),
                                TeleDest("Fremennik Slayer Dungeon", CoordGrid(2805, 10001, 0)),
                                TeleDest("Godwars Dungeon", CoordGrid(2916, 3746, 0)),
                                TeleDest("Jungle Demons", CoordGrid(2715, 9211, 1)),
                                TeleDest("Kalphite Lair", CoordGrid(3226, 3108, 0)),
                                TeleDest("Karuulm Slayer Dungeon", CoordGrid(1311, 10188, 0)),
                                TeleDest("Kraken Cove", CoordGrid(2278, 3609, 0)),
                                TeleDest("Mourner Tunnels", CoordGrid(2029, 4636, 0)),
                                TeleDest("Mos Le'Harmless Caves", CoordGrid(3823, 9425, 0)),
                                TeleDest("Slayer Tower", CoordGrid(3428, 3534, 0)),
                                TeleDest("Smoke Dungeon", CoordGrid(3203, 9379, 0)),
                                TeleDest("Smoke Devil Dungeon", CoordGrid(2412, 3060, 0)),
                                TeleDest("Stronghold Slayer Cave", CoordGrid(2431, 3424, 0)),
                                TeleDest("Taverley Dungeon", CoordGrid(2884, 9799, 0)),
                                TeleDest("Trollheim trollpit", CoordGrid(2884, 3588, 0)),
                                TeleDest("Waterbirth Dungeon", CoordGrid(2443, 10146, 0)),
                                TeleDest("Waterfall Dungeon", CoordGrid(2573, 9866, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Bosses",
                            listOf(
                                TeleDest("Abyssal Sire", CoordGrid(3038, 4771, 0)),
                                TeleDest("Adamant & Runite Dragons", CoordGrid(1568, 5075, 0)),
                                TeleDest("Cave Kraken", CoordGrid(2292, 10008, 0)),
                                TeleDest("Cerberus", CoordGrid(1310, 1252, 0)),
                                TeleDest("Corporeal Beast", CoordGrid(2966, 4382, 2)),
                                TeleDest("Dagannoth Kings", CoordGrid(1912, 4367, 0)),
                                TeleDest("Demonic Gorillas", CoordGrid(2026, 5610, 0)),
                                TeleDest("Elvarg", CoordGrid(2844, 9635, 0)),
                                TeleDest("Giant Mole", CoordGrid(1764, 5179, 0)),
                                TeleDest("God Wars", CoordGrid(2916, 3746, 0)),
                                TeleDest("Kalphite Queen", CoordGrid(3509, 9487, 2)),
                                TeleDest("Lizard Shamans (Canyon)", CoordGrid(1445, 3699, 0)),
                                TeleDest("Mithril Dragons", CoordGrid(1777, 5345, 1)),
                                TeleDest("Thermonuclear Smoke Devils", CoordGrid(2412, 3060, 0)),
                                TeleDest("Vorkath", CoordGrid(2272, 4051, 0)),
                                TeleDest("Zulrah", CoordGrid(2198, 3057, 0)),
                            ),
                        ),
                    ),
                ),
                TeleCat(
                    "Minigames",
                    listOf(
                        TeleGroup(
                            "General",
                            listOf(
                                TeleDest("Last Man Standing", CoordGrid(3400, 3180, 0)),
                                TeleDest("Barrows", CoordGrid(3565, 3313, 0)),
                                TeleDest("Duel Arena", CoordGrid(3367, 3265, 0)),
                                TeleDest("Fight Caves", CoordGrid(2443, 5171, 0)),
                                TeleDest("Motherlode Mine", CoordGrid(3751, 5669, 0)),
                                TeleDest("Puro Puro", CoordGrid(2426, 4443, 0)),
                                TeleDest("Warriors' Guild", CoordGrid(2880, 3546, 0)),
                                TeleDest("Wintertodt", CoordGrid(1630, 3957, 0)),
                                TeleDest("Raids 1", CoordGrid(1254, 3558, 0)),
                                TeleDest("Pest Control", CoordGrid(2659, 2676, 0)),
                            ),
                        )
                    ),
                ),
                TeleCat(
                    "Skilling",
                    listOf(
                        TeleGroup(
                            "Agility",
                            listOf(
                                TeleDest("Gnome Stronghold Course", CoordGrid(2471, 3437, 0)),
                                TeleDest(
                                    "Draynor Village Rooftop Course",
                                    CoordGrid(3105, 3272, 0),
                                ),
                                TeleDest("Al Kharid Rooftop Course", CoordGrid(3281, 3197, 0)),
                                TeleDest("Varrock Rooftop Course", CoordGrid(3224, 3415, 0)),
                                TeleDest("Barbarian Outpost Course", CoordGrid(2552, 3557, 0)),
                                TeleDest("Canifis Rooftop Course", CoordGrid(3505, 3486, 0)),
                                TeleDest("Falador Rooftop Course", CoordGrid(3037, 3339, 0)),
                                TeleDest("Seers' Village Rooftop Course", CoordGrid(2728, 3485, 0)),
                                TeleDest("Rellekka Rooftop Course", CoordGrid(2629, 3677, 0)),
                                TeleDest("Ardougne Rooftop Course", CoordGrid(2673, 3296, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Crafting",
                            listOf(
                                TeleDest("Flax Field", CoordGrid(2741, 3442, 0)),
                                TeleDest("Pottery Oven", CoordGrid(3086, 3409, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Fishing",
                            listOf(
                                TeleDest("Aerial Fishing", CoordGrid(1368, 3633, 0)),
                                TeleDest("Barbarian Village", CoordGrid(3102, 3427, 0)),
                                TeleDest("Catherby Shores", CoordGrid(2809, 3435, 0)),
                                TeleDest("Draynor Shores", CoordGrid(3091, 3225, 0)),
                                TeleDest("Great Kourend Anglers", CoordGrid(1829, 3782, 0)),
                                TeleDest("Karamja Docks", CoordGrid(2925, 3177, 0)),
                                TeleDest("Lumbridge River", CoordGrid(3240, 3251, 0)),
                                TeleDest("Otto's Barbarian Fishing", CoordGrid(2503, 3488, 0)),
                                TeleDest("Piscatoris Fishing Colony", CoordGrid(2341, 3666, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Hunter",
                            listOf(
                                TeleDest("Canifis Swamp (Swamp Lizard)", CoordGrid(3538, 3449, 0)),
                                TeleDest(
                                    "<col=FF4500>(Wilderness) Chinchompa Hill (Black Chinchompa)",
                                    CoordGrid(3145, 3771, 0),
                                ),
                                TeleDest(
                                    "Desert Hunting (Golden Warbler/Orange Salamander)",
                                    CoordGrid(3407, 3073, 0),
                                ),
                                TeleDest("Feldip Hills (Crimson Swift)", CoordGrid(2603, 2932, 0)),
                                TeleDest(
                                    "Gnome-Khazard Battlefield (Red Salamander)",
                                    CoordGrid(2451, 3221, 0),
                                ),
                                TeleDest(
                                    "<col=FF4500>(Wilderness) Hill Giants (Black Salamander)",
                                    CoordGrid(3302, 3668, 0),
                                ),
                                TeleDest(
                                    "Jungle Hunting (Tropical Wagtail/Carnviorous Chinchompa)",
                                    CoordGrid(2533, 2921, 0),
                                ),
                                TeleDest(
                                    "Snow Hunting (Cerulean Twitch)",
                                    CoordGrid(2723, 3771, 0),
                                ),
                                TeleDest(
                                    "Woodland Hunting (Copper Longtail/Chinchompa)",
                                    CoordGrid(2341, 3597, 0),
                                ),
                            ),
                        ),
                        TeleGroup(
                            "Mining",
                            listOf(
                                TeleDest("Dwarven Mine", CoordGrid(3043, 9817, 0)),
                                TeleDest("Essence Mine - Dense", CoordGrid(1769, 3849, 0)),
                                TeleDest("Essence Mine - Regular", CoordGrid(2911, 4831, 0)),
                                TeleDest("Gem Mine", CoordGrid(2825, 2997, 0)),
                                TeleDest("Jatizso Mine", CoordGrid(2406, 10190, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Thieving",
                            listOf(
                                TeleDest("Ardougne Marketplace", CoordGrid(2661, 3305, 0)),
                                TeleDest("Draynor Marketplace", CoordGrid(3082, 3250, 0)),
                                TeleDest("Keldagrim Marketplace", CoordGrid(2899, 10199, 0)),
                                TeleDest("Rogues' Den", CoordGrid(3046, 4969, 1)),
                            ),
                        ),
                        TeleGroup(
                            "Slayer",
                            listOf(
                                TeleDest("Ancient Cavern", CoordGrid(1762, 5361, 0)),
                                TeleDest("Asganian Ice Dungeon", CoordGrid(3006, 9550, 0)),
                                TeleDest("Bandit Camp", CoordGrid(3170, 2982, 0)),
                                TeleDest("Brimhaven Dungeon", CoordGrid(2710, 9564, 0)),
                                TeleDest("Brine Rat Cavern", CoordGrid(2696, 10121, 0)),
                                TeleDest("Catacombs of Kourend", CoordGrid(1665, 10049, 0)),
                                TeleDest("Chasm of Fire", CoordGrid(1435, 3671, 0)),
                                TeleDest("Fremennik Slayer Dungeon", CoordGrid(2805, 10001, 0)),
                                TeleDest("Godwars Dungeon", CoordGrid(2916, 3746, 0)),
                                TeleDest("Kalphite Lair", CoordGrid(3226, 3108, 0)),
                                TeleDest("Kraken Cove", CoordGrid(2278, 3609, 0)),
                                TeleDest("Lithkren Vault", CoordGrid(1568, 5075, 0)),
                                TeleDest("Mourner Tunnels", CoordGrid(2029, 4636, 0)),
                                TeleDest("Mos Le'Harmless Caves", CoordGrid(3823, 9425, 0)),
                                TeleDest("Slayer Tower", CoordGrid(3428, 3534, 0)),
                                TeleDest("Smoke Dungeon", CoordGrid(3203, 9379, 0)),
                                TeleDest("Smoke Devil Dungeon", CoordGrid(2412, 3060, 0)),
                                TeleDest("Stronghold Slayer Cave", CoordGrid(2431, 3424, 0)),
                                TeleDest("Taverley Dungeon", CoordGrid(2884, 9799, 0)),
                                TeleDest("Trollheim trollpit", CoordGrid(2884, 3588, 0)),
                                TeleDest("Waterbirth Dungeon", CoordGrid(2443, 10146, 0)),
                                TeleDest("Waterfall Dungeon", CoordGrid(2573, 9866, 0)),
                            ),
                        ),
                        TeleGroup(
                            "Runecrafting",
                            listOf(
                                TeleDest("Ourania Cave", CoordGrid(3015, 5629, 0)),
                                TeleDest("Abyss", CoordGrid(1762, 5361, 0)),
                            ),
                        ),
                    ),
                ),
            )
    }
}
