package org.rsmod.content.generic.npcs.shops

import org.rsmod.api.shops.config.ShopParams
import org.rsmod.api.type.editors.npc.NpcEditor
import org.rsmod.api.type.refs.npc.NpcReferences

// Generated by work/port-tools/gen_world_shops.py - regenerate, do not hand-edit.
internal object WorldShopNpcRefs : NpcReferences() {
    val ahoy_ghost_shopkeeper = find("ahoy_ghost_shopkeeper")
    val aldarin_food_store = find("aldarin_food_store")
    val aldarin_gem_store = find("aldarin_gem_store")
    val aldarin_general_store = find("aldarin_general_store")
    val aldarin_wine_store = find("aldarin_wine_store")
    val arceuus_generalstore = find("arceuus_generalstore")
    val arceuus_runeshop = find("arceuus_runeshop")
    val arceuus_staffshop = find("arceuus_staffshop")
    val auburn_axe_store = find("auburn_axe_store")
    val auburn_general_store = find("auburn_general_store")
    val auburn_staff_store = find("auburn_staff_store")
    val aubury = find("aubury")
    val baker_merchant = find("baker_merchant")
    val baker_merchant_ardougne = find("baker_merchant_ardougne")
    val baker_merchant_ardougne2 = find("baker_merchant_ardougne2")
    val bedabin = find("bedabin")
    val betty = find("betty")
    val bh_emblem_trader = find("bh_emblem_trader")
    val blurberry = find("blurberry")
    val blurberrybarmen = find("blurberrybarmen")
    val brian = find("brian")
    val burgh_general_store_owner = find("burgh_general_store_owner")
    val cam_torum_shop_baker = find("cam_torum_shop_baker")
    val cam_torum_shop_blacksmith = find("cam_torum_shop_blacksmith")
    val cam_torum_shop_general = find("cam_torum_shop_general")
    val cam_torum_shop_herbalist = find("cam_torum_shop_herbalist")
    val cam_torum_shop_jewellery = find("cam_torum_shop_jewellery")
    val cam_torum_shop_magic = find("cam_torum_shop_magic")
    val cam_torum_shop_mining = find("cam_torum_shop_mining")
    val candle_maker = find("candle_maker")
    val darkm_trader_candles = find("darkm_trader_candles")
    val darkm_trader_clothes = find("darkm_trader_clothes")
    val darkm_trader_food = find("darkm_trader_food")
    val darkm_trader_general = find("darkm_trader_general")
    val darkm_trader_pub = find("darkm_trader_pub")
    val dommik = find("dommik")
    val dorgesh_female_lamp_seller = find("dorgesh_female_lamp_seller")
    val dorgesh_male_bone_seller = find("dorgesh_male_bone_seller")
    val dorgesh_male_ironmonger = find("dorgesh_male_ironmonger")
    val dorgesh_male_leather_seller = find("dorgesh_male_leather_seller")
    val drogo = find("drogo")
    val dt_bandit_shopkeeper = find("dt_bandit_shopkeeper")
    val dwarf_city_blue_trader1 = find("dwarf_city_blue_trader1")
    val dwarf_city_blue_trader2 = find("dwarf_city_blue_trader2")
    val dwarf_city_brown_trader1 = find("dwarf_city_brown_trader1")
    val dwarf_city_brown_trader2 = find("dwarf_city_brown_trader2")
    val dwarf_city_green_trader1 = find("dwarf_city_green_trader1")
    val dwarf_city_green_trader2 = find("dwarf_city_green_trader2")
    val dwarf_city_purple_trader1 = find("dwarf_city_purple_trader1")
    val dwarf_city_purple_trader2 = find("dwarf_city_purple_trader2")
    val dwarf_city_red_trader1 = find("dwarf_city_red_trader1")
    val dwarf_city_red_trader1_multi = find("dwarf_city_red_trader1_multi")
    val dwarf_city_red_trader2 = find("dwarf_city_red_trader2")
    val dwarf_city_red_trader2_multi = find("dwarf_city_red_trader2_multi")
    val dwarf_city_shop_armour = find("dwarf_city_shop_armour")
    val dwarf_city_shop_bakery = find("dwarf_city_shop_bakery")
    val dwarf_city_shop_cloth = find("dwarf_city_shop_cloth")
    val dwarf_city_shop_cloth_poor = find("dwarf_city_shop_cloth_poor")
    val dwarf_city_shop_craft = find("dwarf_city_shop_craft")
    val dwarf_city_shop_gems = find("dwarf_city_shop_gems")
    val dwarf_city_shop_general_store = find("dwarf_city_shop_general_store")
    val dwarf_city_shop_pickaxe = find("dwarf_city_shop_pickaxe")
    val dwarf_city_shop_silver = find("dwarf_city_shop_silver")
    val dwarf_city_shop_warhammer = find("dwarf_city_shop_warhammer")
    val dwarf_city_shop_weapons = find("dwarf_city_shop_weapons")
    val dwarf_city_silver_trader1 = find("dwarf_city_silver_trader1")
    val dwarf_city_silver_trader2 = find("dwarf_city_silver_trader2")
    val dwarf_city_white_trader1 = find("dwarf_city_white_trader1")
    val dwarf_city_white_trader2 = find("dwarf_city_white_trader2")
    val dwarf_city_yellow_trader1 = find("dwarf_city_yellow_trader1")
    val dwarf_city_yellow_trader2 = find("dwarf_city_yellow_trader2")
    val dwarven_shopkeeper = find("dwarven_shopkeeper")
    val elid_choc_ice_seller = find("elid_choc_ice_seller")
    val elid_general_seller = find("elid_general_seller")
    val elid_shield_seller = find("elid_shield_seller")
    val emblem_trader = find("emblem_trader")
    val etc_fish_monger = find("etc_fish_monger")
    val etc_veg_monger = find("etc_veg_monger")
    val farming_shopkeeper_1 = find("farming_shopkeeper_1")
    val farming_shopkeeper_3 = find("farming_shopkeeper_3")
    val farming_shopkeeper_4 = find("farming_shopkeeper_4")
    val fat_tony = find("fat_tony")
    val feud_marketseller = find("feud_marketseller")
    val fever_dodgy_mike = find("fever_dodgy_mike")
    val fever_harpoon_joe = find("fever_harpoon_joe")
    val fever_pirate_two_feet_charley = find("fever_pirate_two_feet_charley")
    val fishguildshop = find("fishguildshop")
    val fortis_shop_baker = find("fortis_shop_baker")
    val fortis_shop_blacksmith = find("fortis_shop_blacksmith")
    val fortis_shop_crafting = find("fortis_shop_crafting")
    val fortis_shop_farming = find("fortis_shop_farming")
    val fortis_shop_food = find("fortis_shop_food")
    val fortis_shop_fur = find("fortis_shop_fur")
    val fortis_shop_gems = find("fortis_shop_gems")
    val fortis_shop_general_1 = find("fortis_shop_general_1")
    val fortis_shop_general_2 = find("fortis_shop_general_2")
    val fortis_shop_maces = find("fortis_shop_maces")
    val fortis_shop_seamstress = find("fortis_shop_seamstress")
    val fortis_shop_silk = find("fortis_shop_silk")
    val fortis_shop_spices = find("fortis_shop_spices")
    val fossil_general_store = find("fossil_general_store")
    val fossil_shopkeeper = find("fossil_shopkeeper")
    val frisd_armourmerchant = find("frisd_armourmerchant")
    val frisd_fishmerchant = find("frisd_fishmerchant")
    val frisd_oremerchant = find("frisd_oremerchant")
    val frisd_weaponmerchant = find("frisd_weaponmerchant")
    val fur_merchant = find("fur_merchant")
    val fur_merchant_ardougne = find("fur_merchant_ardougne")
    val gem_merchant = find("gem_merchant")
    val gem_merchant_ardougne = find("gem_merchant_ardougne")
    val gem_trader = find("gem_trader")
    val generalassistant2 = find("generalassistant2")
    val generalassistant3 = find("generalassistant3")
    val generalassistant5 = find("generalassistant5")
    val generalassistant6 = find("generalassistant6")
    val generalassistant7 = find("generalassistant7")
    val generalassistant8 = find("generalassistant8")
    val generalshopkeeper2 = find("generalshopkeeper2")
    val generalshopkeeper3 = find("generalshopkeeper3")
    val generalshopkeeper4 = find("generalshopkeeper4")
    val generalshopkeeper5 = find("generalshopkeeper5")
    val generalshopkeeper6 = find("generalshopkeeper6")
    val generalshopkeeper7 = find("generalshopkeeper7")
    val generalshopkeeper8 = find("generalshopkeeper8")
    val gnome_gulluck = find("gnome_gulluck")
    val gnome_heckelfunch = find("gnome_heckelfunch")
    val gnome_hudo = find("gnome_hudo")
    val gnome_rometti = find("gnome_rometti")
    val gnomeshopkeeper = find("gnomeshopkeeper")
    val gotr_reward_trader = find("gotr_reward_trader")
    val hg_fur_trader = find("hg_fur_trader")
    val hg_mixedhide_seller = find("hg_mixedhide_seller")
    val horvik_the_armourer = find("horvik_the_armourer")
    val hosidius_farmingstore = find("hosidius_farmingstore")
    val hosidius_foodstore = find("hosidius_foodstore")
    val hosidius_generalstore = find("hosidius_generalstore")
    val hunting_shop_owner_nardah = find("hunting_shop_owner_nardah")
    val hunting_shop_owner_yanille = find("hunting_shop_owner_yanille")
    val jiminua = find("jiminua")
    val kastori_farming_trader = find("kastori_farming_trader")
    val kastori_fishing_trader = find("kastori_fishing_trader")
    val kastori_general_store = find("kastori_general_store")
    val kebab_seller = find("kebab_seller")
    val kebos_farming_store = find("kebos_farming_store")
    val kebos_seed_merchant = find("kebos_seed_merchant")
    val khazard_shopkeeper = find("khazard_shopkeeper")
    val lathas_shopkeeper = find("lathas_shopkeeper")
    val louie_legs = find("louie_legs")
    val lovakengj_generalstore = find("lovakengj_generalstore")
    val lowe = find("lowe")
    val lunar_moonclan_baba_yaga = find("lunar_moonclan_baba_yaga")
    val magearena_runeshop = find("magearena_runeshop")
    val magic_store_owner = find("magic_store_owner")
    val magic_store_owner2 = find("magic_store_owner2")
    val merchant_pies = find("merchant_pies")
    val mguild_oreseller = find("mguild_oreseller")
    val mguild_pickaxeseller = find("mguild_pickaxeseller")
    val misc_fish_monger = find("misc_fish_monger")
    val misc_veg_monger = find("misc_veg_monger")
    val mistrock_mining_store = find("mistrock_mining_store")
    val mistrock_shield_store = find("mistrock_shield_store")
    val mm2_javelinstoreowner = find("mm2_javelinstoreowner")
    val mm_daga = find("mm_daga")
    val mm_hamab = find("mm_hamab")
    val mm_ifaba = find("mm_ifaba")
    val mm_solihib = find("mm_solihib")
    val mm_tutab = find("mm_tutab")
    val mourning_bow_seller = find("mourning_bow_seller")
    val mourning_seamstress = find("mourning_seamstress")
    val mourning_stores_man = find("mourning_stores_man")
    val myths_guild_weapon_seller = find("myths_guild_weapon_seller")
    val nurmof = find("nurmof")
    val ogre_merchant = find("ogre_merchant")
    val ogre_trader1 = find("ogre_trader1")
    val ogre_trader2 = find("ogre_trader2")
    val oziach = find("oziach")
    val peksa = find("peksa")
    val pest_squire_rangeshop = find("pest_squire_rangeshop")
    val pest_squire_runeshop = find("pest_squire_runeshop")
    val pest_squire_storemaster = find("pest_squire_storemaster")
    val piscarilius_fish_trader = find("piscarilius_fish_trader")
    val piscarilius_generalstore_keeper = find("piscarilius_generalstore_keeper")
    val prif_generalstore = find("prif_generalstore")
    val prif_seamstress = find("prif_seamstress")
    val quetzacalli_general_store = find("quetzacalli_general_store")
    val ranael = find("ranael")
    val ranging_guild_armour_salesman = find("ranging_guild_armour_salesman")
    val ranging_guild_bow_salesman = find("ranging_guild_bow_salesman")
    val ranging_guild_tribal_salesman = find("ranging_guild_tribal_salesman")
    val razmire_keelgan = find("razmire_keelgan")
    val regicidegeneralshopkeeper = find("regicidegeneralshopkeeper")
    val roguesden_trader = find("roguesden_trader")
    val rommik = find("rommik")
    val royal_clotheshop_owner = find("royal_clotheshop_owner")
    val royal_foodshop_owner = find("royal_foodshop_owner")
    val royal_generalstore_owner = find("royal_generalstore_owner")
    val sailing_transport_trader_stan_aldarin = find("sailing_transport_trader_stan_aldarin")
    val sailing_transport_trader_stan_brimhaven = find("sailing_transport_trader_stan_brimhaven")
    val sailing_transport_trader_stan_catherby = find("sailing_transport_trader_stan_catherby")
    val sailing_transport_trader_stan_corsaircove =
        find("sailing_transport_trader_stan_corsaircove")
    val sailing_transport_trader_stan_fortis = find("sailing_transport_trader_stan_fortis")
    val sailing_transport_trader_stan_landsend = find("sailing_transport_trader_stan_landsend")
    val sailing_transport_trader_stan_mosleharmless =
        find("sailing_transport_trader_stan_mosleharmless")
    val sailing_transport_trader_stan_musapoint = find("sailing_transport_trader_stan_musapoint")
    val sailing_transport_trader_stan_piscarilius =
        find("sailing_transport_trader_stan_piscarilius")
    val sailing_transport_trader_stan_portkhazard =
        find("sailing_transport_trader_stan_portkhazard")
    val sailing_transport_trader_stan_portphasmatys =
        find("sailing_transport_trader_stan_portphasmatys")
    val sailing_transport_trader_stan_portsarim = find("sailing_transport_trader_stan_portsarim")
    val sailing_transport_trader_stan_porttyras = find("sailing_transport_trader_stan_porttyras")
    val sailing_transport_trader_stan_prifddinas = find("sailing_transport_trader_stan_prifddinas")
    val sailing_transport_trader_stan_shipyard = find("sailing_transport_trader_stan_shipyard")
    val sailing_transport_trader_stan_sunsetcoast =
        find("sailing_transport_trader_stan_sunsetcoast")
    val sailing_transport_trader_stan_tempestus = find("sailing_transport_trader_stan_tempestus")
    val salvager_overlook_general_store = find("salvager_overlook_general_store")
    val salvager_overlook_platebody_store = find("salvager_overlook_platebody_store")
    val scavvo = find("scavvo")
    val seed_merchant = find("seed_merchant")
    val shantay = find("shantay")
    val shayzien_armourshop = find("shayzien_armourshop")
    val shayzien_clothesshop = find("shayzien_clothesshop")
    val shayzien_generalstore = find("shayzien_generalstore")
    val shayzien_rangeshop = find("shayzien_rangeshop")
    val shayzien_weaponshop = find("shayzien_weaponshop")
    val shilogeneralstore = find("shilogeneralstore")
    val silk_merchant = find("silk_merchant")
    val silk_merchant_ardougne = find("silk_merchant_ardougne")
    val silk_trader = find("silk_trader")
    val silver_merchant_ardougne = find("silver_merchant_ardougne")
    val smithing_guild_ore_seller = find("smithing_guild_ore_seller")
    val spice_merchant = find("spice_merchant")
    val spice_merchant_ardougne = find("spice_merchant_ardougne")
    val sunset_coast_fishing_shop = find("sunset_coast_fishing_shop")
    val sunset_coast_general_store = find("sunset_coast_general_store")
    val sunset_coast_helmet_shop = find("sunset_coast_helmet_shop")
    val swamp_candle_guy = find("swamp_candle_guy")
    val swordshop1 = find("swordshop1")
    val swordshop2 = find("swordshop2")
    val tal_teklan_archery_trader = find("tal_teklan_archery_trader")
    val tal_teklan_dye_trader = find("tal_teklan_dye_trader")
    val tal_teklan_general_store = find("tal_teklan_general_store")
    val tal_teklan_rune_trader = find("tal_teklan_rune_trader")
    val tea_seller = find("tea_seller")
    val thessalia = find("thessalia")
    val treevillage_shopkeeper1 = find("treevillage_shopkeeper1")
    val uncerter_jiminua = find("uncerter_jiminua")
    val uncerter_pollnivneach = find("uncerter_pollnivneach")
    val viking_clothing_shopkeeper = find("viking_clothing_shopkeeper")
    val viking_fish_monger = find("viking_fish_monger")
    val viking_fur_monger = find("viking_fur_monger")
    val viking_weapons_salesman = find("viking_weapons_salesman")
    val warguild_armour_shopkeeper = find("warguild_armour_shopkeeper")
    val warguild_food_shopkeeper = find("warguild_food_shopkeeper")
    val warguild_potion_shopkeeper = find("warguild_potion_shopkeeper")
    val warrens_fishmonger = find("warrens_fishmonger")
    val warrens_shopkeeper = find("warrens_shopkeeper")
    val wcguild_axeseller = find("wcguild_axeseller")
    val werewolfinnkeeper = find("werewolfinnkeeper")
    val werewolfshopkeeper1 = find("werewolfshopkeeper1")
    val werewolfshopkeeper2 = find("werewolfshopkeeper2")
    val werewolfshopkeeper3 = find("werewolfshopkeeper3")
    val wilderness_capeseller_1 = find("wilderness_capeseller_1")
    val wilderness_capeseller_10 = find("wilderness_capeseller_10")
    val wilderness_capeseller_2 = find("wilderness_capeseller_2")
    val wilderness_capeseller_3 = find("wilderness_capeseller_3")
    val wilderness_capeseller_4 = find("wilderness_capeseller_4")
    val wilderness_capeseller_5 = find("wilderness_capeseller_5")
    val wilderness_capeseller_7 = find("wilderness_capeseller_7")
    val wilderness_capeseller_8 = find("wilderness_capeseller_8")
    val wilderness_capeseller_9 = find("wilderness_capeseller_9")
    val wydin = find("wydin")
    val zaff = find("zaff")
    val zeke = find("zeke")
}

/**
 * Wires every vanilla shopkeeper npc type to its shop inventory via [ShopParams.npc_shop].
 * `ShopkeeperScript` binds the npc's Trade/Shop op at startup, so every spawn of the type opens the
 * shop regardless of coordinates. Npcs that already carry `npc_shop` (Unforge edits) or explicit
 * shop scripts (Lumbridge) are deliberately absent.
 */
internal object WorldShopEdits : NpcEditor() {
    init {
        shopkeeper(
            WorldShopNpcRefs.ahoy_ghost_shopkeeper,
            "ahoy_generalshop",
            "Port Phasmatys General Store",
        )
        shopkeeper(WorldShopNpcRefs.aldarin_food_store, "aldarin_food_store", "Aldarin Food Store")
        shopkeeper(WorldShopNpcRefs.aldarin_gem_store, "aldarin_gem_store", "Aldarin Gem Store")
        shopkeeper(
            WorldShopNpcRefs.aldarin_general_store,
            "aldarin_general_store",
            "Aldarin General Store",
        )
        shopkeeper(WorldShopNpcRefs.aldarin_wine_store, "aldarin_wine_store", "Aldarin Wine Store")
        shopkeeper(WorldShopNpcRefs.arceuus_generalstore, "generalshop4", "Arceuus General Store")
        shopkeeper(WorldShopNpcRefs.arceuus_runeshop, "runeshop", "Regath's Wares")
        shopkeeper(WorldShopNpcRefs.arceuus_staffshop, "staffshop", "Arceuus Staff Shop")
        shopkeeper(WorldShopNpcRefs.auburn_axe_store, "lunami_axe_store", "Lunami's Axe Store")
        shopkeeper(
            WorldShopNpcRefs.auburn_general_store,
            "auburn_general_store",
            "Auburnvale General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.auburn_staff_store,
            "sebamo_staff_store",
            "Sebamo's Staff Store",
        )
        shopkeeper(WorldShopNpcRefs.aubury, "runeshop", "Aubury's Rune Shop")
        shopkeeper(WorldShopNpcRefs.baker_merchant, "foodshop", "Bakery Stall")
        shopkeeper(WorldShopNpcRefs.baker_merchant_ardougne, "foodshop", "Ardougne Bakery Stall")
        shopkeeper(WorldShopNpcRefs.baker_merchant_ardougne2, "foodshop", "Ardougne Bakery Stall")
        shopkeeper(WorldShopNpcRefs.bedabin, "bedabincampshop", "Bedabin Nomad Supplies")
        shopkeeper(WorldShopNpcRefs.betty, "magicshop", "Betty's Magic Emporium")
        // bh_emblem_trader intentionally unbound: pvpa_shop_inv is the bounty-emblem reward
        // shop and no emblem currency/earning path exists - a gp fallback would misprice it.
        shopkeeper(WorldShopNpcRefs.blurberry, "boozeshop", "Blurberry's Bar")
        shopkeeper(WorldShopNpcRefs.blurberrybarmen, "boozeshop", "Blurberry's Bar")
        shopkeeper(WorldShopNpcRefs.brian, "battleaxeshop", "Brian's Battleaxe Bazaar")
        shopkeeper(
            WorldShopNpcRefs.burgh_general_store_owner,
            "burgh_general_store",
            "Burgh de Rott General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.cam_torum_shop_baker,
            "cam_torum_shop_baker",
            "Cam Torum Bakery",
        )
        shopkeeper(
            WorldShopNpcRefs.cam_torum_shop_blacksmith,
            "cam_torum_shop_blacksmith",
            "Cam Torum Blacksmith",
        )
        shopkeeper(
            WorldShopNpcRefs.cam_torum_shop_general,
            "cam_torum_shop_general",
            "Cam Torum General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.cam_torum_shop_herbalist,
            "cam_torum_shop_herbalist",
            "Cam Torum Herbalist",
        )
        shopkeeper(
            WorldShopNpcRefs.cam_torum_shop_jewellery,
            "cam_torum_shop_jewellery",
            "Cam Torum Jewellery",
        )
        shopkeeper(
            WorldShopNpcRefs.cam_torum_shop_magic,
            "cam_torum_shop_magic",
            "Cam Torum Magic Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.cam_torum_shop_mining,
            "cam_torum_shop_mining",
            "Cam Torum Mining Shop",
        )
        shopkeeper(WorldShopNpcRefs.candle_maker, "candleshop", "Candle Shop")
        shopkeeper(WorldShopNpcRefs.darkm_trader_candles, "candleshop", "Darkmeyer Candle Trader")
        shopkeeper(WorldShopNpcRefs.darkm_trader_clothes, "clotheshop", "Darkmeyer Clothes Trader")
        shopkeeper(WorldShopNpcRefs.darkm_trader_food, "foodshop", "Darkmeyer Food Trader")
        shopkeeper(
            WorldShopNpcRefs.darkm_trader_general,
            "generalshop2",
            "Darkmeyer General Trader",
        )
        shopkeeper(WorldShopNpcRefs.darkm_trader_pub, "boozeshop", "Darkmeyer Pub")
        shopkeeper(WorldShopNpcRefs.dommik, "craftingshop", "Dommik's Crafting Store")
        shopkeeper(WorldShopNpcRefs.dorgesh_female_lamp_seller, "dorgesh_lamp_shop", "Lamp Seller")
        shopkeeper(
            WorldShopNpcRefs.dorgesh_male_bone_seller,
            "dorgesh_general_store",
            "Bone Seller",
        )
        shopkeeper(WorldShopNpcRefs.dorgesh_male_ironmonger, "dorgeshuun_weapon_shop", "Ironmonger")
        shopkeeper(
            WorldShopNpcRefs.dorgesh_male_leather_seller,
            "dorgesh_leather_shop",
            "Leather Seller",
        )
        shopkeeper(WorldShopNpcRefs.drogo, "miningstore", "Drogo's Mining Emporium")
        shopkeeper(WorldShopNpcRefs.dt_bandit_shopkeeper, "dt_bandit_shop", "Bandit Bargains")
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_blue_trader1,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_blue_trader2,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_brown_trader1,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_brown_trader2,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_green_trader1,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_green_trader2,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_purple_trader1,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_purple_trader2,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_red_trader1,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_red_trader1_multi,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_red_trader2,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_red_trader2_multi,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_armour,
            "keldagrim_quality_armour_shop",
            "Quality Armour Shop",
        )
        shopkeeper(WorldShopNpcRefs.dwarf_city_shop_bakery, "foodshop", "Keldagrim's Best Bread")
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_cloth,
            "keldagrim_clothes_shop",
            "Vermundi's Clothes Stall",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_cloth_poor,
            "keldagrim_clothes_shop",
            "Vermundi's Clothes Stall",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_craft,
            "craftingshop2",
            "Carefree Crafting Stall",
        )
        shopkeeper(WorldShopNpcRefs.dwarf_city_shop_gems, "gemshop3", "Green Gemstone Gems")
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_general_store,
            "keldagrim_general_shop",
            "Keldagrim's Best Bread",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_pickaxe,
            "keldagrim_pickaxe_shop",
            "Nolar's Pickaxes",
        )
        shopkeeper(WorldShopNpcRefs.dwarf_city_shop_silver, "silvershop", "Silver Cog Silver Stall")
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_warhammer,
            "keldagrim_warhammer_shop",
            "Vigr's Warhammers",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_shop_weapons,
            "keldagrim_quality_weapons_shop",
            "Quality Weapons Shop",
        )
        shopkeeper(WorldShopNpcRefs.dwarf_city_silver_trader1, "silvershop", "Keldagrim Trader")
        shopkeeper(WorldShopNpcRefs.dwarf_city_silver_trader2, "silvershop", "Keldagrim Trader")
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_white_trader1,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_white_trader2,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_yellow_trader1,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.dwarf_city_yellow_trader2,
            "keldagrim_general_shop",
            "Keldagrim Trader",
        )
        shopkeeper(WorldShopNpcRefs.dwarven_shopkeeper, "generalshop3", "Dwarven Shopping Store")
        shopkeeper(WorldShopNpcRefs.elid_choc_ice_seller, "chociceshopnardah", "Rokuh's Choc-Ices")
        shopkeeper(
            WorldShopNpcRefs.elid_general_seller,
            "generalshopnardah",
            "Nardah General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.elid_shield_seller,
            "armourshopnardah",
            "Seddu's Adventurers' Store",
        )
        // emblem_trader intentionally unbound for the same reason as bh_emblem_trader above.
        shopkeeper(WorldShopNpcRefs.etc_fish_monger, "fishingshop", "Fish Monger")
        shopkeeper(WorldShopNpcRefs.etc_veg_monger, "foodshop", "Vegetable Seller")
        shopkeeper(WorldShopNpcRefs.farming_shopkeeper_1, "farming_shop_1", "Farming Supplies")
        shopkeeper(WorldShopNpcRefs.farming_shopkeeper_3, "farming_shop_3", "Farming Supplies")
        shopkeeper(WorldShopNpcRefs.farming_shopkeeper_4, "farming_shop_4", "Farming Supplies")
        shopkeeper(WorldShopNpcRefs.fat_tony, "pizzabaseshop", "Fat Tony's Pizza Bases")
        shopkeeper(WorldShopNpcRefs.feud_marketseller, "pollnivneach_generalstore", "Market Seller")
        shopkeeper(
            WorldShopNpcRefs.fever_dodgy_mike,
            "mikeshop",
            "Dodgy Mike's Second-hand Clothing",
        )
        shopkeeper(WorldShopNpcRefs.fever_harpoon_joe, "joeshop", "Harpoon Joe's House of Rum")
        shopkeeper(
            WorldShopNpcRefs.fever_pirate_two_feet_charley,
            "charleyshop",
            "Two Feet Charley's Fish Shop",
        )
        shopkeeper(WorldShopNpcRefs.fishguildshop, "fishingshop2", "Fishing Guild Shop")
        shopkeeper(WorldShopNpcRefs.fortis_shop_baker, "fortis_shop_baker", "Fortis Bakery")
        shopkeeper(
            WorldShopNpcRefs.fortis_shop_blacksmith,
            "fortis_shop_blacksmith",
            "Fortis Blacksmith",
        )
        shopkeeper(
            WorldShopNpcRefs.fortis_shop_crafting,
            "fortis_shop_crafting",
            "Fortis Crafting Store",
        )
        shopkeeper(
            WorldShopNpcRefs.fortis_shop_farming,
            "fortis_shop_farming",
            "Fortis Farming Store",
        )
        shopkeeper(WorldShopNpcRefs.fortis_shop_food, "fortis_shop_food", "Fortis Food Store")
        shopkeeper(WorldShopNpcRefs.fortis_shop_fur, "fortis_shop_fur", "Fortis Fur Trader")
        shopkeeper(WorldShopNpcRefs.fortis_shop_gems, "fortis_shop_gems", "Fortis Gem Trader")
        shopkeeper(
            WorldShopNpcRefs.fortis_shop_general_1,
            "fortis_shop_general_1",
            "Fortis General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.fortis_shop_general_2,
            "fortis_shop_general_2",
            "Fortis General Store",
        )
        shopkeeper(WorldShopNpcRefs.fortis_shop_maces, "fortis_shop_maces", "Fortis Mace Shop")
        shopkeeper(
            WorldShopNpcRefs.fortis_shop_seamstress,
            "fortis_shop_seamstress",
            "Fortis Seamstress",
        )
        shopkeeper(WorldShopNpcRefs.fortis_shop_silk, "fortis_shop_silk", "Fortis Silk Trader")
        shopkeeper(WorldShopNpcRefs.fortis_shop_spices, "fortis_shop_spices", "Fortis Spice Trader")
        shopkeeper(
            WorldShopNpcRefs.fossil_general_store,
            "fossil_general_store",
            "Fossil Island General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.fossil_shopkeeper,
            "fossil_general_store",
            "Fossil Island General Store",
        )
        shopkeeper(WorldShopNpcRefs.frisd_armourmerchant, "frisd_armourshop", "Armour Merchant")
        shopkeeper(WorldShopNpcRefs.frisd_fishmerchant, "frisb_n_shop", "Fish Merchant")
        shopkeeper(WorldShopNpcRefs.frisd_oremerchant, "frisd_oreshop", "Ore Merchant")
        shopkeeper(WorldShopNpcRefs.frisd_weaponmerchant, "frisd_weaponshop", "Weapon Merchant")
        shopkeeper(WorldShopNpcRefs.fur_merchant, "furshop", "Fur Merchant")
        shopkeeper(WorldShopNpcRefs.fur_merchant_ardougne, "furshop", "Ardougne Fur Stall")
        shopkeeper(WorldShopNpcRefs.gem_merchant, "gemshop", "Gem Merchant")
        shopkeeper(WorldShopNpcRefs.gem_merchant_ardougne, "gemshop2", "Ardougne Gem Stall")
        shopkeeper(WorldShopNpcRefs.gem_trader, "gemshop", "Gem Trader")
        shopkeeper(WorldShopNpcRefs.generalassistant2, "generalshop2", "General Store")
        shopkeeper(WorldShopNpcRefs.generalassistant3, "generalshop3", "General Store")
        shopkeeper(WorldShopNpcRefs.generalassistant5, "generalshop5", "General Store")
        shopkeeper(WorldShopNpcRefs.generalassistant6, "generalshop6", "General Store")
        shopkeeper(WorldShopNpcRefs.generalassistant7, "generalshop7", "General Store")
        shopkeeper(WorldShopNpcRefs.generalassistant8, "generalshop8", "General Store")
        shopkeeper(WorldShopNpcRefs.generalshopkeeper2, "generalshop2", "General Store")
        shopkeeper(WorldShopNpcRefs.generalshopkeeper3, "generalshop3", "General Store")
        shopkeeper(WorldShopNpcRefs.generalshopkeeper4, "generalshop4", "General Store")
        shopkeeper(WorldShopNpcRefs.generalshopkeeper5, "generalshop5", "General Store")
        shopkeeper(WorldShopNpcRefs.generalshopkeeper6, "generalshop6", "General Store")
        shopkeeper(WorldShopNpcRefs.generalshopkeeper7, "generalshop7", "General Store")
        shopkeeper(WorldShopNpcRefs.generalshopkeeper8, "generalshop8", "General Store")
        shopkeeper(WorldShopNpcRefs.gnome_gulluck, "gnomeshop_gulluck", "Gulluck and Sons")
        shopkeeper(WorldShopNpcRefs.gnome_heckelfunch, "gnomeshop_heck", "Heckel Funch's Groceries")
        shopkeeper(WorldShopNpcRefs.gnome_hudo, "gnomeshop_hudo", "Hudo's Grand Tree Groceries")
        shopkeeper(WorldShopNpcRefs.gnome_rometti, "gnomeshop_rometti", "Rometti's Fine Fashions")
        shopkeeper(WorldShopNpcRefs.gnomeshopkeeper, "gnomeshop", "Grand Tree Groceries")
        shopkeeper(
            WorldShopNpcRefs.gotr_reward_trader,
            "gotr_reward_shop_all",
            "Guardians of the Rift Rewards",
        )
        shopkeeper(WorldShopNpcRefs.hg_fur_trader, "fur_shop_guild", "Hunter Guild Fur Trader")
        shopkeeper(
            WorldShopNpcRefs.hg_mixedhide_seller,
            "hunting_shop_guild",
            "Hunter Guild Mixed Hide Shop",
        )
        shopkeeper(WorldShopNpcRefs.horvik_the_armourer, "armourshop", "Horvik's Armour Shop")
        shopkeeper(
            WorldShopNpcRefs.hosidius_farmingstore,
            "farming_shop_3",
            "Hosidius Farming Store",
        )
        shopkeeper(WorldShopNpcRefs.hosidius_foodstore, "foodshop", "Hosidius Food Store")
        shopkeeper(WorldShopNpcRefs.hosidius_generalstore, "generalshop3", "Hosidius General Store")
        shopkeeper(
            WorldShopNpcRefs.hunting_shop_owner_nardah,
            "hunting_shop_nardah",
            "Nardah Hunter Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.hunting_shop_owner_yanille,
            "hunting_shop_yanille",
            "Aleck's Hunter Emporium",
        )
        shopkeeper(WorldShopNpcRefs.jiminua, "junglestore", "Jiminua's Jungle Store")
        shopkeeper(
            WorldShopNpcRefs.kastori_farming_trader,
            "kastorifarmingstore",
            "Kastori Farming Store",
        )
        shopkeeper(
            WorldShopNpcRefs.kastori_fishing_trader,
            "kastorifishingstore",
            "Kastori Fishing Store",
        )
        shopkeeper(
            WorldShopNpcRefs.kastori_general_store,
            "kastori_general_store",
            "Kastori General Store",
        )
        shopkeeper(WorldShopNpcRefs.kebab_seller, "foodshop", "Kebab Seller")
        shopkeeper(
            WorldShopNpcRefs.kebos_farming_store,
            "kebos_farming_equipment_shop",
            "Farming Supplies",
        )
        shopkeeper(WorldShopNpcRefs.kebos_seed_merchant, "kebos_farming_seed_shop", "Seed Merchant")
        shopkeeper(WorldShopNpcRefs.khazard_shopkeeper, "khazardshop", "Khazard General Store")
        shopkeeper(
            WorldShopNpcRefs.lathas_shopkeeper,
            "lathastrainingstore",
            "Lathas' Training Store",
        )
        shopkeeper(WorldShopNpcRefs.louie_legs, "legsshop", "Louie's Armoured Legs Bazaar")
        shopkeeper(
            WorldShopNpcRefs.lovakengj_generalstore,
            "generalshop5",
            "Lovakengj General Store",
        )
        shopkeeper(WorldShopNpcRefs.lowe, "archeryshop", "Lowe's Archery Emporium")
        shopkeeper(
            WorldShopNpcRefs.lunar_moonclan_baba_yaga,
            "lunar_runeshop",
            "Baba Yaga's Magic Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.magearena_runeshop,
            "magearena_runeshop",
            "Mage Arena Rune Shop",
        )
        shopkeeper(WorldShopNpcRefs.magic_store_owner, "magicguildshop", "Magic Guild Store")
        shopkeeper(WorldShopNpcRefs.magic_store_owner2, "magicguildshop2", "Magic Guild Robe Store")
        shopkeeper(WorldShopNpcRefs.merchant_pies, "shop_pies", "Pie Shop")
        shopkeeper(WorldShopNpcRefs.mguild_oreseller, "mguild_oreshop", "Ore Seller")
        shopkeeper(WorldShopNpcRefs.mguild_pickaxeseller, "mguild_pickaxeshop", "Pickaxe Seller")
        shopkeeper(WorldShopNpcRefs.misc_fish_monger, "fishingshop", "Fish Monger")
        shopkeeper(WorldShopNpcRefs.misc_veg_monger, "foodshop", "Vegetable Seller")
        shopkeeper(
            WorldShopNpcRefs.mistrock_mining_store,
            "mistrock_mining_store",
            "Mistrock Mining Store",
        )
        shopkeeper(
            WorldShopNpcRefs.mistrock_shield_store,
            "mistrock_shield_store",
            "Mistrock Shield Store",
        )
        shopkeeper(WorldShopNpcRefs.mm2_javelinstoreowner, "mm2_javelin_store", "Javelin Store")
        shopkeeper(WorldShopNpcRefs.mm_daga, "mm_scimitar_shop", "Daga's Scimitar Smithy")
        shopkeeper(WorldShopNpcRefs.mm_hamab, "mm_crafting_shop", "Hamab's Crafting Emporium")
        shopkeeper(WorldShopNpcRefs.mm_ifaba, "mm_general_shop", "Ifaba's General Store")
        shopkeeper(WorldShopNpcRefs.mm_solihib, "mm_food_shop", "Solihib's Food Stall")
        shopkeeper(WorldShopNpcRefs.mm_tutab, "mm_magic_shop", "Tutab's Magical Market")
        shopkeeper(
            WorldShopNpcRefs.mourning_bow_seller,
            "lletyaarcheryshop1",
            "Lletya Archery Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.mourning_seamstress,
            "lletyaseamstressshop1",
            "Lletya Seamstress",
        )
        shopkeeper(
            WorldShopNpcRefs.mourning_stores_man,
            "lletyageneralshop1",
            "Lletya General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.myths_guild_weapon_seller,
            "runiteshop",
            "Myths' Guild Weaponry",
        )
        shopkeeper(WorldShopNpcRefs.nurmof, "pickaxeshop", "Nurmof's Pickaxe Shop")
        shopkeeper(WorldShopNpcRefs.ogre_merchant, "generalshopogre", "Ogre General Store")
        shopkeeper(WorldShopNpcRefs.ogre_trader1, "generalshopogre", "Ogre General Store")
        shopkeeper(WorldShopNpcRefs.ogre_trader2, "herbloreshopogre", "Ogre Herblore Supplies")
        shopkeeper(WorldShopNpcRefs.oziach, "runeplateshop", "Oziach's Armour")
        shopkeeper(WorldShopNpcRefs.peksa, "helmetshop", "Peksa's Helmet Shop")
        shopkeeper(
            WorldShopNpcRefs.pest_squire_rangeshop,
            "pest_archery_store",
            "Void Knight Archery Store",
        )
        shopkeeper(
            WorldShopNpcRefs.pest_squire_runeshop,
            "pest_rune_store",
            "Void Knight Rune Store",
        )
        shopkeeper(
            WorldShopNpcRefs.pest_squire_storemaster,
            "pest_general_store",
            "Void Knight General Store",
        )
        shopkeeper(WorldShopNpcRefs.piscarilius_fish_trader, "fishingshop", "Fish Trader")
        shopkeeper(
            WorldShopNpcRefs.piscarilius_generalstore_keeper,
            "piscarilius_generalstore",
            "Frankie's Fishing Emporium",
        )
        shopkeeper(WorldShopNpcRefs.prif_generalstore, "generalshop7", "Prifddinas General Store")
        shopkeeper(
            WorldShopNpcRefs.prif_seamstress,
            "lletyaseamstressshop1",
            "Prifddinas Seamstress",
        )
        shopkeeper(
            WorldShopNpcRefs.quetzacalli_general_store,
            "quetzacalli_general_store",
            "Quetzacalli General Store",
        )
        shopkeeper(WorldShopNpcRefs.ranael, "skirtshop", "Ranael's Super Skirt Store")
        shopkeeper(
            WorldShopNpcRefs.ranging_guild_armour_salesman,
            "ranging_guild_armourshop",
            "Ranging Guild Armourer",
        )
        shopkeeper(
            WorldShopNpcRefs.ranging_guild_bow_salesman,
            "ranging_guild_bowshop",
            "Ranging Guild Bow Salesman",
        )
        shopkeeper(
            WorldShopNpcRefs.ranging_guild_tribal_salesman,
            "ranging_guild_tribalshop",
            "Ranging Guild Tribal Shop",
        )
        shopkeeper(WorldShopNpcRefs.razmire_keelgan, "razmiregeneralstore", "Razmire General Store")
        shopkeeper(
            WorldShopNpcRefs.regicidegeneralshopkeeper,
            "regicide_general_shop",
            "General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.roguesden_trader,
            "roguesden_shop",
            "Martin Thwait's Lost and Found",
        )
        shopkeeper(WorldShopNpcRefs.rommik, "craftingshop2", "Rommik's Crafty Supplies")
        shopkeeper(
            WorldShopNpcRefs.royal_clotheshop_owner,
            "royal_clotheshop",
            "Miscellanian Clothes Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.royal_foodshop_owner,
            "royal_foodshop",
            "Miscellanian Food Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.royal_generalstore_owner,
            "royal_generalstore",
            "Miscellanian General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_aldarin,
            "trader_shop_aldarin",
            "Aldarin Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_brimhaven,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_catherby,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_corsaircove,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_fortis,
            "trader_shop_fortis",
            "Civitas illa Fortis Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_landsend,
            "trader_shop_landsend",
            "Land's End Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_mosleharmless,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_musapoint,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_piscarilius,
            "trader_shop_piscarilius",
            "Port Piscarilius Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_portkhazard,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_portphasmatys,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_portsarim,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_porttyras,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_prifddinas,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_shipyard,
            "trader_stan_shop",
            "Trader Stan's Trading Post",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_sunsetcoast,
            "trader_shop_sunsetcoast",
            "Sunset Coast Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.sailing_transport_trader_stan_tempestus,
            "trader_shop_tempestus",
            "Tempestus Trader",
        )
        shopkeeper(
            WorldShopNpcRefs.salvager_overlook_general_store,
            "salvager_overlook_general_store",
            "Salvager Overlook General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.salvager_overlook_platebody_store,
            "salvager_overlook_platebody_store",
            "Salvager Overlook Platebody Store",
        )
        shopkeeper(WorldShopNpcRefs.scavvo, "runiteshop", "Scavvo's Rune Store")
        shopkeeper(WorldShopNpcRefs.seed_merchant, "farming_shop_1", "Olivia's Seed Market")
        shopkeeper(WorldShopNpcRefs.shantay, "shantayshop", "Shantay Pass Shop")
        shopkeeper(WorldShopNpcRefs.shayzien_armourshop, "armourshop", "Shayzien Armour Shop")
        shopkeeper(
            WorldShopNpcRefs.shayzien_clothesshop,
            "shayzien_clothesshop",
            "Shayzien Clothes Shop",
        )
        shopkeeper(WorldShopNpcRefs.shayzien_generalstore, "generalshop6", "Shayzien General Store")
        shopkeeper(
            WorldShopNpcRefs.shayzien_rangeshop,
            "shayzien_rangeshop",
            "Shayzien Ranged Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.shayzien_weaponshop,
            "kebos_weapon_shop",
            "Shayzien Weapon Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.shilogeneralstore,
            "shilojunglestore",
            "Shilo Village General Store",
        )
        shopkeeper(WorldShopNpcRefs.silk_merchant, "clotheshop", "Silk Merchant")
        shopkeeper(WorldShopNpcRefs.silk_merchant_ardougne, "clotheshop", "Ardougne Silk Stall")
        shopkeeper(WorldShopNpcRefs.silk_trader, "clotheshop", "Silk Trader")
        shopkeeper(WorldShopNpcRefs.silver_merchant_ardougne, "silvershop", "Ardougne Silver Stall")
        shopkeeper(WorldShopNpcRefs.smithing_guild_ore_seller, "smithsshop", "Smithing Supplies")
        shopkeeper(WorldShopNpcRefs.spice_merchant, "spiceshop", "Spice Merchant")
        shopkeeper(WorldShopNpcRefs.spice_merchant_ardougne, "spiceshop", "Ardougne Spice Stall")
        shopkeeper(
            WorldShopNpcRefs.sunset_coast_fishing_shop,
            "sunset_coast_fishing_shop",
            "Sunset Coast Fishing Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.sunset_coast_general_store,
            "sunset_coast_general_store",
            "Sunset Coast General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.sunset_coast_helmet_shop,
            "sunset_coast_helmet_shop",
            "Sunset Coast Helmet Shop",
        )
        shopkeeper(WorldShopNpcRefs.swamp_candle_guy, "candleshop", "Candle Maker")
        shopkeeper(WorldShopNpcRefs.swordshop1, "swordshop", "Varrock Swordshop")
        shopkeeper(WorldShopNpcRefs.swordshop2, "swordshop", "Varrock Swordshop")
        shopkeeper(
            WorldShopNpcRefs.tal_teklan_archery_trader,
            "tal_teklan_archershop",
            "Tal Teklan Archery Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.tal_teklan_dye_trader,
            "tal_teklan_dyeshop",
            "Tal Teklan Dye Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.tal_teklan_general_store,
            "tal_teklan_generalstore",
            "Tal Teklan General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.tal_teklan_rune_trader,
            "tal_teklan_runeshop",
            "Tal Teklan Rune Shop",
        )
        shopkeeper(WorldShopNpcRefs.tea_seller, "teashop", "Tea Stall")
        shopkeeper(WorldShopNpcRefs.thessalia, "clotheshop", "Thessalia's Fine Clothes")
        shopkeeper(
            WorldShopNpcRefs.treevillage_shopkeeper1,
            "generalshop7",
            "Tree Gnome Village Store",
        )
        shopkeeper(WorldShopNpcRefs.uncerter_jiminua, "junglestore", "Jiminua's Jungle Store")
        shopkeeper(
            WorldShopNpcRefs.uncerter_pollnivneach,
            "pollnivneach_generalstore",
            "Pollnivneach General Store",
        )
        shopkeeper(
            WorldShopNpcRefs.viking_clothing_shopkeeper,
            "viking_clothes_shop",
            "Rellekka Clothing Store",
        )
        shopkeeper(WorldShopNpcRefs.viking_fish_monger, "fishingshop", "Fish Monger")
        shopkeeper(WorldShopNpcRefs.viking_fur_monger, "viking_furshop", "Fur Trader")
        shopkeeper(
            WorldShopNpcRefs.viking_weapons_salesman,
            "viking_weapons_shop",
            "Rellekka Weapons Store",
        )
        shopkeeper(
            WorldShopNpcRefs.warguild_armour_shopkeeper,
            "warguild_armour_shop",
            "Warrior Guild Armoury",
        )
        shopkeeper(
            WorldShopNpcRefs.warguild_food_shopkeeper,
            "warguild_food_shop",
            "Warrior Guild Food Shop",
        )
        shopkeeper(
            WorldShopNpcRefs.warguild_potion_shopkeeper,
            "warguild_potion_shop",
            "Warrior Guild Potion Shop",
        )
        shopkeeper(WorldShopNpcRefs.warrens_fishmonger, "fishingshop", "Fish Monger")
        shopkeeper(WorldShopNpcRefs.warrens_shopkeeper, "generalshop8", "The Warrens General Store")
        shopkeeper(WorldShopNpcRefs.wcguild_axeseller, "axeshop", "Woodcutting Guild Axe Shop")
        shopkeeper(WorldShopNpcRefs.werewolfinnkeeper, "boozeshop", "Hair of the Dog Tavern")
        shopkeeper(
            WorldShopNpcRefs.werewolfshopkeeper1,
            "werewolfgeneralstore",
            "Canifis General Store",
        )
        shopkeeper(WorldShopNpcRefs.werewolfshopkeeper2, "werewolfstore1", "Canifis General Store")
        shopkeeper(WorldShopNpcRefs.werewolfshopkeeper3, "werewolfstore2", "Barkers' Haberdashery")
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_1,
            "wildernesscapeshop1",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_10,
            "wildernesscapeshop10",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_2,
            "wildernesscapeshop2",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_3,
            "wildernesscapeshop3",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_4,
            "wildernesscapeshop4",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_5,
            "wildernesscapeshop5",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_7,
            "wildernesscapeshop7",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_8,
            "wildernesscapeshop8",
            "Team Cape Seller",
        )
        shopkeeper(
            WorldShopNpcRefs.wilderness_capeseller_9,
            "wildernesscapeshop9",
            "Team Cape Seller",
        )
        shopkeeper(WorldShopNpcRefs.wydin, "wydinstore", "Wydin's Food Store")
        shopkeeper(WorldShopNpcRefs.zaff, "staffshop", "Zaff's Superior Staffs")
        shopkeeper(WorldShopNpcRefs.zeke, "scimitarshop", "Zeke's Superior Scimitars")
    }

    private fun NpcEditor.shopkeeper(
        npc: org.rsmod.game.type.npc.NpcType,
        shop: String,
        title: String,
    ) {
        edit(npc) {
            param[ShopParams.npc_shop] = shop
            param[ShopParams.npc_shop_title] = title
        }
    }
}
