CREATE TABLE IF NOT EXISTS early_game_progression (
    character_id INTEGER PRIMARY KEY REFERENCES characters(id) ON DELETE CASCADE,
    starter_relic TEXT,
    relic_selected INTEGER NOT NULL DEFAULT 0,
    last_relic_change_epoch INTEGER,
    completed_milestones TEXT NOT NULL DEFAULT '',
    claimed_milestone_rewards TEXT NOT NULL DEFAULT '',
    first_bond_unlocked INTEGER NOT NULL DEFAULT 0,
    first_bond_completed INTEGER NOT NULL DEFAULT 0,
    starter_companion_selected INTEGER NOT NULL DEFAULT 0,
    starter_companion_id TEXT,
    companion_tutorial_completed INTEGER NOT NULL DEFAULT 0,
    companion_basics TEXT NOT NULL DEFAULT '',
    discoveries TEXT NOT NULL DEFAULT '',
    discovery_points INTEGER NOT NULL DEFAULT 0,
    discovery_reward_milestones TEXT NOT NULL DEFAULT '',
    world_find_statistics TEXT NOT NULL DEFAULT '',
    world_find_available_at_epoch INTEGER NOT NULL DEFAULT 0,
    tracker_minimized INTEGER NOT NULL DEFAULT 0,
    tracker_hidden INTEGER NOT NULL DEFAULT 0,
    legacy_player INTEGER NOT NULL DEFAULT 0,
    trial_active INTEGER NOT NULL DEFAULT 0,
    trial_attempts INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
