package org.rsmod.api.companion

public object CompanionTalentCatalog {
    public val definitions: List<CompanionTalentDefinition> =
        listOf(
            CompanionTalentDefinition(
                "guardian-vitality",
                CompanionClass.TANK,
                1,
                effectKey = "max-health-percent",
            ),
            CompanionTalentDefinition(
                "iron-stance",
                CompanionClass.TANK,
                2,
                effectKey = "damage-reduction-percent",
            ),
            CompanionTalentDefinition(
                "taunting-roar",
                CompanionClass.TANK,
                3,
                effectKey = "taunt-radius",
            ),
            CompanionTalentDefinition(
                "bulwark",
                CompanionClass.TANK,
                4,
                effectKey = "owner-damage-shield",
            ),
            CompanionTalentDefinition(
                "last-stand",
                CompanionClass.TANK,
                5,
                effectKey = "incapacitated-delay",
            ),
            CompanionTalentDefinition(
                "unyielding",
                CompanionClass.TANK,
                6,
                effectKey = "boss-damage-reduction",
            ),
            CompanionTalentDefinition(
                "guardian-aegis",
                CompanionClass.TANK,
                7,
                effectKey = "owner-protection",
            ),
            CompanionTalentDefinition(
                "immortal-oath",
                CompanionClass.TANK,
                8,
                maxRanks = 1,
                effectKey = "death-prevention",
                capstone = true,
            ),
            CompanionTalentDefinition(
                "mending-light",
                CompanionClass.SUPPORT,
                1,
                effectKey = "heal-power",
            ),
            CompanionTalentDefinition(
                "battle-hymn",
                CompanionClass.SUPPORT,
                2,
                effectKey = "owner-stat-buff",
            ),
            CompanionTalentDefinition(
                "cleanse",
                CompanionClass.SUPPORT,
                3,
                effectKey = "cleanse-debuff",
            ),
            CompanionTalentDefinition(
                "warding-sigil",
                CompanionClass.SUPPORT,
                4,
                effectKey = "shield-power",
            ),
            CompanionTalentDefinition(
                "renewal",
                CompanionClass.SUPPORT,
                5,
                effectKey = "heal-over-time",
            ),
            CompanionTalentDefinition(
                "mana-thread",
                CompanionClass.SUPPORT,
                6,
                effectKey = "ability-cooldown",
            ),
            CompanionTalentDefinition(
                "rescue",
                CompanionClass.SUPPORT,
                7,
                effectKey = "emergency-heal",
            ),
            CompanionTalentDefinition(
                "life-anchor",
                CompanionClass.SUPPORT,
                8,
                maxRanks = 1,
                effectKey = "owner-death-save",
                capstone = true,
            ),
            CompanionTalentDefinition(
                "vicious-strikes",
                CompanionClass.DPS,
                1,
                effectKey = "damage-percent",
            ),
            CompanionTalentDefinition(
                "executioner",
                CompanionClass.DPS,
                2,
                effectKey = "low-health-damage",
            ),
            CompanionTalentDefinition(
                "rapid-assault",
                CompanionClass.DPS,
                3,
                effectKey = "attack-speed",
            ),
            CompanionTalentDefinition(
                "critical-focus",
                CompanionClass.DPS,
                4,
                effectKey = "critical-rate",
            ),
            CompanionTalentDefinition(
                "elemental-edge",
                CompanionClass.DPS,
                5,
                effectKey = "ability-power",
            ),
            CompanionTalentDefinition(
                "blood-price",
                CompanionClass.DPS,
                6,
                effectKey = "life-steal",
            ),
            CompanionTalentDefinition(
                "relentless",
                CompanionClass.DPS,
                7,
                effectKey = "proc-chance",
            ),
            CompanionTalentDefinition(
                "annihilation",
                CompanionClass.DPS,
                8,
                maxRanks = 1,
                effectKey = "burst-ability",
                capstone = true,
            ),

            // Extended Tank branch: defensive passives and active control abilities.
            CompanionTalentDefinition(
                "thick-hide",
                CompanionClass.TANK,
                1,
                effectKey = "armour-percent",
            ),
            CompanionTalentDefinition(
                "fortified-core",
                CompanionClass.TANK,
                2,
                effectKey = "stagger-resistance",
                prerequisites = listOf("thick-hide"),
            ),
            CompanionTalentDefinition(
                "shield-bash",
                CompanionClass.TANK,
                3,
                effectKey = "shield-bash",
                type = CompanionTalentType.ACTIVE,
                abilityId = "shield-bash",
                prerequisites = listOf("fortified-core"),
            ),
            CompanionTalentDefinition(
                "unyielding-wall",
                CompanionClass.TANK,
                4,
                effectKey = "block-chance",
                prerequisites = listOf("shield-bash"),
            ),
            CompanionTalentDefinition(
                "challenging-shout",
                CompanionClass.TANK,
                5,
                effectKey = "challenging-shout",
                type = CompanionTalentType.ACTIVE,
                abilityId = "challenging-shout",
                prerequisites = listOf("unyielding-wall"),
            ),
            CompanionTalentDefinition(
                "spiked-armour",
                CompanionClass.TANK,
                6,
                effectKey = "reflect-damage",
                prerequisites = listOf("challenging-shout"),
            ),
            CompanionTalentDefinition(
                "guardian-link",
                CompanionClass.TANK,
                7,
                effectKey = "owner-damage-share",
                prerequisites = listOf("spiked-armour"),
            ),
            CompanionTalentDefinition(
                "iron-bastion",
                CompanionClass.TANK,
                8,
                maxRanks = 1,
                effectKey = "iron-bastion",
                type = CompanionTalentType.ULTIMATE,
                abilityId = "iron-bastion",
                prerequisites = listOf("guardian-link"),
                capstone = true,
            ),
            CompanionTalentDefinition(
                "steady-footing",
                CompanionClass.TANK,
                1,
                effectKey = "knockback-resistance",
            ),
            CompanionTalentDefinition(
                "vanguard",
                CompanionClass.TANK,
                2,
                effectKey = "frontline-damage",
                prerequisites = listOf("steady-footing"),
            ),
            CompanionTalentDefinition(
                "intercept",
                CompanionClass.TANK,
                3,
                effectKey = "intercept",
                type = CompanionTalentType.ACTIVE,
                abilityId = "intercept",
                prerequisites = listOf("vanguard"),
            ),
            CompanionTalentDefinition(
                "fortress-mind",
                CompanionClass.TANK,
                4,
                effectKey = "control-resistance",
                prerequisites = listOf("intercept"),
            ),
            CompanionTalentDefinition(
                "protective-stance",
                CompanionClass.TANK,
                5,
                effectKey = "protective-stance",
                type = CompanionTalentType.TRIGGERED,
                abilityId = "protective-stance",
                prerequisites = listOf("fortress-mind"),
            ),
            CompanionTalentDefinition(
                "aegis-recharge",
                CompanionClass.TANK,
                6,
                effectKey = "shield-recharge",
                prerequisites = listOf("protective-stance"),
            ),
            CompanionTalentDefinition(
                "last-guardian",
                CompanionClass.TANK,
                7,
                effectKey = "last-guardian",
                type = CompanionTalentType.TRIGGERED,
                abilityId = "last-guardian",
                prerequisites = listOf("aegis-recharge"),
            ),
            CompanionTalentDefinition(
                "unyielding-fortress",
                CompanionClass.TANK,
                8,
                maxRanks = 1,
                effectKey = "unyielding-fortress",
                type = CompanionTalentType.ULTIMATE,
                abilityId = "unyielding-fortress",
                prerequisites = listOf("last-guardian"),
                capstone = true,
            ),

            // Extended Support branch: healing, cleansing and utility abilities.
            CompanionTalentDefinition(
                "soothing-presence",
                CompanionClass.SUPPORT,
                1,
                effectKey = "passive-healing",
            ),
            CompanionTalentDefinition(
                "focused-mending",
                CompanionClass.SUPPORT,
                2,
                effectKey = "single-target-heal",
                prerequisites = listOf("soothing-presence"),
            ),
            CompanionTalentDefinition(
                "mending-wave",
                CompanionClass.SUPPORT,
                3,
                effectKey = "mending-wave",
                type = CompanionTalentType.ACTIVE,
                abilityId = "mending-wave",
                prerequisites = listOf("focused-mending"),
            ),
            CompanionTalentDefinition(
                "purifying-light",
                CompanionClass.SUPPORT,
                4,
                effectKey = "purifying-light",
                type = CompanionTalentType.ACTIVE,
                abilityId = "purifying-light",
                prerequisites = listOf("mending-wave"),
            ),
            CompanionTalentDefinition(
                "resonant-hymn",
                CompanionClass.SUPPORT,
                5,
                effectKey = "group-stat-buff",
                prerequisites = listOf("purifying-light"),
            ),
            CompanionTalentDefinition(
                "mana-reserve",
                CompanionClass.SUPPORT,
                6,
                effectKey = "resource-regeneration",
                prerequisites = listOf("resonant-hymn"),
            ),
            CompanionTalentDefinition(
                "guardian-rescue",
                CompanionClass.SUPPORT,
                7,
                effectKey = "guardian-rescue",
                type = CompanionTalentType.TRIGGERED,
                abilityId = "guardian-rescue",
                prerequisites = listOf("mana-reserve"),
            ),
            CompanionTalentDefinition(
                "divine-intervention",
                CompanionClass.SUPPORT,
                8,
                maxRanks = 1,
                effectKey = "divine-intervention",
                type = CompanionTalentType.ULTIMATE,
                abilityId = "divine-intervention",
                prerequisites = listOf("guardian-rescue"),
                capstone = true,
            ),
            CompanionTalentDefinition(
                "alchemical-aid",
                CompanionClass.SUPPORT,
                1,
                effectKey = "potion-effect",
            ),
            CompanionTalentDefinition(
                "swift-recovery",
                CompanionClass.SUPPORT,
                2,
                effectKey = "recovery-speed",
                prerequisites = listOf("alchemical-aid"),
            ),
            CompanionTalentDefinition(
                "dispel-pulse",
                CompanionClass.SUPPORT,
                3,
                effectKey = "dispel-pulse",
                type = CompanionTalentType.ACTIVE,
                abilityId = "dispel-pulse",
                prerequisites = listOf("swift-recovery"),
            ),
            CompanionTalentDefinition(
                "shared-vitality",
                CompanionClass.SUPPORT,
                4,
                effectKey = "shared-vitality",
                prerequisites = listOf("dispel-pulse"),
            ),
            CompanionTalentDefinition(
                "rallying-call",
                CompanionClass.SUPPORT,
                5,
                effectKey = "rallying-call",
                type = CompanionTalentType.ACTIVE,
                abilityId = "rallying-call",
                prerequisites = listOf("shared-vitality"),
            ),
            CompanionTalentDefinition(
                "cooldown-weaving",
                CompanionClass.SUPPORT,
                6,
                effectKey = "cooldown-weaving",
                prerequisites = listOf("rallying-call"),
            ),
            CompanionTalentDefinition(
                "second-wind",
                CompanionClass.SUPPORT,
                7,
                effectKey = "second-wind",
                type = CompanionTalentType.TRIGGERED,
                abilityId = "second-wind",
                prerequisites = listOf("cooldown-weaving"),
            ),
            CompanionTalentDefinition(
                "everlasting-aid",
                CompanionClass.SUPPORT,
                8,
                maxRanks = 1,
                effectKey = "everlasting-aid",
                type = CompanionTalentType.ULTIMATE,
                abilityId = "everlasting-aid",
                prerequisites = listOf("second-wind"),
                capstone = true,
            ),

            // Extended DPS branch: burst, mobility and execute abilities.
            CompanionTalentDefinition(
                "combat-instinct",
                CompanionClass.DPS,
                1,
                effectKey = "accuracy-percent",
            ),
            CompanionTalentDefinition(
                "predator",
                CompanionClass.DPS,
                2,
                effectKey = "target-damage",
                prerequisites = listOf("combat-instinct"),
            ),
            CompanionTalentDefinition(
                "focused-volley",
                CompanionClass.DPS,
                3,
                effectKey = "focused-volley",
                type = CompanionTalentType.ACTIVE,
                abilityId = "focused-volley",
                prerequisites = listOf("predator"),
            ),
            CompanionTalentDefinition(
                "crippling-strike",
                CompanionClass.DPS,
                4,
                effectKey = "crippling-strike",
                type = CompanionTalentType.ACTIVE,
                abilityId = "crippling-strike",
                prerequisites = listOf("focused-volley"),
            ),
            CompanionTalentDefinition(
                "momentum",
                CompanionClass.DPS,
                5,
                effectKey = "momentum",
                type = CompanionTalentType.TRIGGERED,
                abilityId = "momentum",
                prerequisites = listOf("crippling-strike"),
            ),
            CompanionTalentDefinition(
                "siphoning-blows",
                CompanionClass.DPS,
                6,
                effectKey = "siphoning-blows",
                prerequisites = listOf("momentum"),
            ),
            CompanionTalentDefinition(
                "death-mark",
                CompanionClass.DPS,
                7,
                effectKey = "death-mark",
                type = CompanionTalentType.ACTIVE,
                abilityId = "death-mark",
                prerequisites = listOf("siphoning-blows"),
            ),
            CompanionTalentDefinition(
                "perfect-execution",
                CompanionClass.DPS,
                8,
                maxRanks = 1,
                effectKey = "perfect-execution",
                type = CompanionTalentType.ULTIMATE,
                abilityId = "perfect-execution",
                prerequisites = listOf("death-mark"),
                capstone = true,
            ),
            CompanionTalentDefinition(
                "opportunist",
                CompanionClass.DPS,
                1,
                effectKey = "damage-vs-wounded",
            ),
            CompanionTalentDefinition(
                "weapon-mastery",
                CompanionClass.DPS,
                2,
                effectKey = "weapon-mastery",
                prerequisites = listOf("opportunist"),
            ),
            CompanionTalentDefinition(
                "shadow-step",
                CompanionClass.DPS,
                3,
                effectKey = "shadow-step",
                type = CompanionTalentType.ACTIVE,
                abilityId = "shadow-step",
                prerequisites = listOf("weapon-mastery"),
            ),
            CompanionTalentDefinition(
                "exposed-weakness",
                CompanionClass.DPS,
                4,
                effectKey = "exposed-weakness",
                prerequisites = listOf("shadow-step"),
            ),
            CompanionTalentDefinition(
                "frenzy",
                CompanionClass.DPS,
                5,
                effectKey = "frenzy",
                type = CompanionTalentType.ACTIVE,
                abilityId = "frenzy",
                prerequisites = listOf("exposed-weakness"),
            ),
            CompanionTalentDefinition(
                "relentless-hunt",
                CompanionClass.DPS,
                6,
                effectKey = "relentless-hunt",
                prerequisites = listOf("frenzy"),
            ),
            CompanionTalentDefinition(
                "execution-window",
                CompanionClass.DPS,
                7,
                effectKey = "execution-window",
                type = CompanionTalentType.TRIGGERED,
                abilityId = "execution-window",
                prerequisites = listOf("relentless-hunt"),
            ),
            CompanionTalentDefinition(
                "apex-predator",
                CompanionClass.DPS,
                8,
                maxRanks = 1,
                effectKey = "apex-predator",
                type = CompanionTalentType.ULTIMATE,
                abilityId = "apex-predator",
                prerequisites = listOf("execution-window"),
                capstone = true,
            ),
        )

    public val byId: Map<String, CompanionTalentDefinition> = definitions.associateBy { it.id }

    /** Short player-facing descriptions for passive talents (ability talents use the catalog). */
    private val descriptions: Map<String, String> =
        mapOf(
            "guardian-vitality" to "+10 max hitpoints per rank",
            "iron-stance" to "+5 max hitpoints per rank",
            "taunting-roar" to "Taunts nearby enemies to attack",
            "bulwark" to "+15 max hitpoints per rank",
            "last-stand" to "Delays incapacitation when downed",
            "unyielding" to "Reduces damage taken from bosses",
            "guardian-aegis" to "Shields the owner from damage",
            "immortal-oath" to "+50 HP; prevents death once",
            "thick-hide" to "Increases armour per rank",
            "fortified-core" to "Resists stagger effects per rank",
            "unyielding-wall" to "Chance to block attacks per rank",
            "spiked-armour" to "Reflects damage back per rank",
            "guardian-link" to "Shares damage with the owner",
            "steady-footing" to "Resists knockback per rank",
            "vanguard" to "Bonus damage on the frontline",
            "fortress-mind" to "Resists control effects per rank",
            "aegis-recharge" to "Shields recharge faster per rank",
            "mending-light" to "+5% healing power per rank",
            "battle-hymn" to "+3% support power per rank",
            "cleanse" to "Periodically cleanses the owner",
            "warding-sigil" to "+4% support power per rank",
            "renewal" to "Heals the owner over time",
            "mana-thread" to "Reduces ability cooldowns per rank",
            "rescue" to "Emergency heal when owner is low",
            "life-anchor" to "+25% support; saves owner once",
            "soothing-presence" to "Passively heals the owner",
            "focused-mending" to "Stronger single-target heals",
            "resonant-hymn" to "Buffs the group per rank",
            "mana-reserve" to "Regenerates resources per rank",
            "alchemical-aid" to "Improves potion effects per rank",
            "swift-recovery" to "Faster recovery per rank",
            "shared-vitality" to "Shares healing with the owner",
            "cooldown-weaving" to "Shorter cooldowns per rank",
            "vicious-strikes" to "+5% damage per rank",
            "executioner" to "+4% damage per rank",
            "rapid-assault" to "Attacks faster per rank",
            "critical-focus" to "Higher crit chance per rank",
            "elemental-edge" to "+3% damage per rank",
            "blood-price" to "Heals for part of damage dealt",
            "relentless" to "Higher proc chance per rank",
            "annihilation" to "+25% damage; burst attack",
            "combat-instinct" to "Increased accuracy per rank",
            "predator" to "Bonus damage to the target",
            "siphoning-blows" to "Restores resources on hit",
            "exposed-weakness" to "Weakens enemy defence per rank",
            "relentless-hunt" to "Sustains hunt bonuses per rank",
            "opportunist" to "Bonus damage vs wounded foes",
            "weapon-mastery" to "Improves weapon effectiveness",
        )

    public fun definition(id: String): CompanionTalentDefinition =
        byId[id] ?: error("Unknown companion talent: $id")

    /** Human-readable effect text shown on the talent card. */
    public fun description(def: CompanionTalentDefinition): String {
        val abilityId = def.abilityId
        if (abilityId != null) {
            return CompanionAbilityCatalog.definition(abilityId).description
        }
        return descriptions[def.id] ?: def.effectKey
    }
}
