package org.rsmod.content.generic.npcs.banker

import org.rsmod.api.config.refs.content
import org.rsmod.api.type.editors.npc.NpcEditor
import org.rsmod.api.type.refs.npc.NpcReferences

// Generated by work/port-tools/gen_bank_edits.py — regenerate, do not hand-edit.
// All banker-named npc types get the banker content group so Talk-to/Bank/
// Collect/banknote ops work everywhere, not only on the Lumbridge banker.
internal object BankerNpcAllRefs : NpcReferences() {
    val misc_banker = find("misc_banker")
    val mourning_elf_bankerm = find("mourning_elf_bankerm")
    val mourning_elf_bankerf = find("mourning_elf_bankerf")
    val banker1 = find("banker1")
    val uncerter_pollnivneach = find("uncerter_pollnivneach")
    val banker2 = find("banker2")
    val banker1_west = find("banker1_west")
    val banker1_east = find("banker1_east")
    val wom_banker1 = find("wom_banker1")
    val wom_banker2 = find("wom_banker2")
    val wom_banker3 = find("wom_banker3")
    val dorgesh_female_banker = find("dorgesh_female_banker")
    val dorgesh_male_banker = find("dorgesh_male_banker")
    val dwarf_city_banker1 = find("dwarf_city_banker1")
    val dwarf_city_banker2 = find("dwarf_city_banker2")
    val werewolfbanker = find("werewolfbanker")
    val banker1_new = find("banker1_new")
    val banker2_new = find("banker2_new")
    val ahoy_ghost_banker = find("ahoy_ghost_banker")
    val banker2_east = find("banker2_east")
    val kharidbanker1 = find("kharidbanker1")
    val kharidbanker2 = find("kharidbanker2")
    val fairy_banker = find("fairy_banker")
    val shilobanker = find("shilobanker")
    val falador_banker = find("falador_banker")
    val noobbanker = find("noobbanker")
    val lunar_moonclan_monk_man = find("lunar_moonclan_monk_man")
    val contact_banker_male = find("contact_banker_male")
    val contact_banker_female = find("contact_banker_female")
    val fever_banker_01 = find("fever_banker_01")
    val fever_banker_02 = find("fever_banker_02")
    val elid_banker = find("elid_banker")
    val gnomebanker = find("gnomebanker")
    val shayzien_banker_m_north = find("shayzien_banker_m_north")
    val shayzien_banker_m_east = find("shayzien_banker_m_east")
    val shayzien_banker_m_west = find("shayzien_banker_m_west")
    val shayzien_banker_f_north = find("shayzien_banker_f_north")
    val shayzien_banker_f_east = find("shayzien_banker_f_east")
    val shayzien_banker_f_west = find("shayzien_banker_f_west")
    val hosidius_banker_m_west = find("hosidius_banker_m_west")
    val hosidius_banker_m_east = find("hosidius_banker_m_east")
    val hosidius_banker_f_west = find("hosidius_banker_f_west")
    val hosidius_banker_f_east = find("hosidius_banker_f_east")
    val piscarilius_banker_1 = find("piscarilius_banker_1")
    val piscarilius_banker_2 = find("piscarilius_banker_2")
    val arceuus_banker_1_west = find("arceuus_banker_1_west")
    val arceuus_banker_1_east = find("arceuus_banker_1_east")
    val arceuus_banker_2_west = find("arceuus_banker_2_west")
    val arceuus_banker_2_east = find("arceuus_banker_2_east")
    val lovakengj_banker_f_west = find("lovakengj_banker_f_west")
    val lovakengj_banker_f_north = find("lovakengj_banker_f_north")
    val lovakengj_banker_f_east = find("lovakengj_banker_f_east")
    val lovakengj_banker_f_south = find("lovakengj_banker_f_south")
    val lovakengj_banker_m_east = find("lovakengj_banker_m_east")
    val lovakengj_banker_m_south = find("lovakengj_banker_m_south")
    val vampyre_banker_female = find("vampyre_banker_female")
    val vampyre_banker_male = find("vampyre_banker_male")
    val farming_guild_banker1 = find("farming_guild_banker1")
    val farming_guild_banker2 = find("farming_guild_banker2")
    val varrock_bank_doorguard = find("varrock_bank_doorguard")
    val prif_bankerm1 = find("prif_bankerm1")
    val prif_bankerm2 = find("prif_bankerm2")
    val prif_bankerm3 = find("prif_bankerm3")
    val prif_bankerm4 = find("prif_bankerm4")
    val prif_bankerf1 = find("prif_bankerf1")
    val prif_bankerf2 = find("prif_bankerf2")
    val tut2_bank_tutor = find("tut2_bank_tutor")
    val darkm_banker_female = find("darkm_banker_female")
    val darkm_banker_male = find("darkm_banker_male")
    val wildy_hub_banker = find("wildy_hub_banker")
    val clan_hall_banker_0 = find("clan_hall_banker_0")
    val clan_hall_banker_1 = find("clan_hall_banker_1")
    val clan_hall_banker_2 = find("clan_hall_banker_2")
    val clan_hall_banker_3 = find("clan_hall_banker_3")
    val toa_bank_camel = find("toa_bank_camel")
    val cam_torum_banker_1 = find("cam_torum_banker_1")
    val cam_torum_banker_2 = find("cam_torum_banker_2")
    val cam_torum_banker_3 = find("cam_torum_banker_3")
    val cam_torum_banker_4 = find("cam_torum_banker_4")
    val hg_bank_buffalo = find("hg_bank_buffalo")
    val hg_banker_dwarf = find("hg_banker_dwarf")
    val varlamore_banker_s_1 = find("varlamore_banker_s_1")
    val varlamore_banker_s_2 = find("varlamore_banker_s_2")
    val varlamore_banker_s_3 = find("varlamore_banker_s_3")
    val varlamore_banker_s_4 = find("varlamore_banker_s_4")
    val varlamore_banker_n_1 = find("varlamore_banker_n_1")
    val varlamore_banker_n_2 = find("varlamore_banker_n_2")
    val varlamore_banker_n_3 = find("varlamore_banker_n_3")
    val varlamore_banker_n_4 = find("varlamore_banker_n_4")
    val varlamore_banker_e_1 = find("varlamore_banker_e_1")
    val varlamore_banker_e_2 = find("varlamore_banker_e_2")
    val varlamore_banker_e_3 = find("varlamore_banker_e_3")
    val varlamore_banker_e_4 = find("varlamore_banker_e_4")
    val varlamore_banker_w_1 = find("varlamore_banker_w_1")
    val varlamore_banker_w_2 = find("varlamore_banker_w_2")
    val varlamore_banker_w_3 = find("varlamore_banker_w_3")
    val varlamore_banker_w_4 = find("varlamore_banker_w_4")
    val mistrock_banker_1 = find("mistrock_banker_1")
    val mistrock_banker_2 = find("mistrock_banker_2")
    val auburnvale_banker_west_1 = find("auburnvale_banker_west_1")
    val auburnvale_banker_east_1 = find("auburnvale_banker_east_1")
    val auburnvale_banker_south_1 = find("auburnvale_banker_south_1")
    val auburnvale_banker_north_1 = find("auburnvale_banker_north_1")
    val tal_teklan_banker = find("tal_teklan_banker")
    val cw_banker_14847 = find("cw_banker_14847")
    val cw_banker_15496 = find("cw_banker_15496")
    val aide_tutor_banker = find("aide_tutor_banker")
}

internal object BankerAllNpcEditor : NpcEditor() {
    init {
        edit(BankerNpcAllRefs.misc_banker) { contentGroup = content.banker } // 766 Banker
        edit(BankerNpcAllRefs.mourning_elf_bankerm) { contentGroup = content.banker } // 1479 Banker
        edit(BankerNpcAllRefs.mourning_elf_bankerf) { contentGroup = content.banker } // 1480 Banker
        edit(BankerNpcAllRefs.banker1) { contentGroup = content.banker } // 1613 Banker
        edit(BankerNpcAllRefs.uncerter_pollnivneach) {
            contentGroup = content.banker
        } // 1615 Banknote Exchange Merchant
        edit(BankerNpcAllRefs.banker2) { contentGroup = content.banker } // 1618 Banker
        edit(BankerNpcAllRefs.banker1_west) { contentGroup = content.banker } // 1633 Banker
        edit(BankerNpcAllRefs.banker1_east) { contentGroup = content.banker } // 1634 Banker
        edit(BankerNpcAllRefs.wom_banker1) { contentGroup = content.banker } // 2117 Banker
        edit(BankerNpcAllRefs.wom_banker2) { contentGroup = content.banker } // 2118 Banker
        edit(BankerNpcAllRefs.wom_banker3) { contentGroup = content.banker } // 2119 Banker
        edit(BankerNpcAllRefs.dorgesh_female_banker) {
            contentGroup = content.banker
        } // 2292 Banker
        edit(BankerNpcAllRefs.dorgesh_male_banker) { contentGroup = content.banker } // 2293 Banker
        edit(BankerNpcAllRefs.dwarf_city_banker1) { contentGroup = content.banker } // 2368 Banker
        edit(BankerNpcAllRefs.dwarf_city_banker2) { contentGroup = content.banker } // 2369 Banker
        edit(BankerNpcAllRefs.werewolfbanker) { contentGroup = content.banker } // 2633 Banker
        edit(BankerNpcAllRefs.banker1_new) { contentGroup = content.banker } // 2897 Banker
        edit(BankerNpcAllRefs.banker2_new) { contentGroup = content.banker } // 2898 Banker
        edit(BankerNpcAllRefs.ahoy_ghost_banker) {
            contentGroup = content.banker
        } // 3003 Ghost banker
        edit(BankerNpcAllRefs.banker2_east) { contentGroup = content.banker } // 3089 Banker
        edit(BankerNpcAllRefs.kharidbanker1) { contentGroup = content.banker } // 3090 Banker
        edit(BankerNpcAllRefs.kharidbanker2) { contentGroup = content.banker } // 3091 Banker
        edit(BankerNpcAllRefs.fairy_banker) { contentGroup = content.banker } // 3092 Banker
        edit(BankerNpcAllRefs.shilobanker) { contentGroup = content.banker } // 3093 Banker
        edit(BankerNpcAllRefs.falador_banker) { contentGroup = content.banker } // 3094 Banker
        edit(BankerNpcAllRefs.noobbanker) { contentGroup = content.banker } // 3318 Banker
        edit(BankerNpcAllRefs.lunar_moonclan_monk_man) {
            contentGroup = content.banker
        } // 3843 Sirsal Banker
        edit(BankerNpcAllRefs.contact_banker_male) { contentGroup = content.banker } // 3887 Banker
        edit(BankerNpcAllRefs.contact_banker_female) {
            contentGroup = content.banker
        } // 3888 Banker
        edit(BankerNpcAllRefs.fever_banker_01) { contentGroup = content.banker } // 4054 Banker
        edit(BankerNpcAllRefs.fever_banker_02) { contentGroup = content.banker } // 4055 Banker
        edit(BankerNpcAllRefs.elid_banker) { contentGroup = content.banker } // 4762 Nardah Banker
        edit(BankerNpcAllRefs.gnomebanker) { contentGroup = content.banker } // 6084 Gnome banker
        edit(BankerNpcAllRefs.shayzien_banker_m_north) {
            contentGroup = content.banker
        } // 6859 Banker
        edit(BankerNpcAllRefs.shayzien_banker_m_east) {
            contentGroup = content.banker
        } // 6860 Banker
        edit(BankerNpcAllRefs.shayzien_banker_m_west) {
            contentGroup = content.banker
        } // 6861 Banker
        edit(BankerNpcAllRefs.shayzien_banker_f_north) {
            contentGroup = content.banker
        } // 6862 Banker
        edit(BankerNpcAllRefs.shayzien_banker_f_east) {
            contentGroup = content.banker
        } // 6863 Banker
        edit(BankerNpcAllRefs.shayzien_banker_f_west) {
            contentGroup = content.banker
        } // 6864 Banker
        edit(BankerNpcAllRefs.hosidius_banker_m_west) {
            contentGroup = content.banker
        } // 6939 Banker
        edit(BankerNpcAllRefs.hosidius_banker_m_east) {
            contentGroup = content.banker
        } // 6940 Banker
        edit(BankerNpcAllRefs.hosidius_banker_f_west) {
            contentGroup = content.banker
        } // 6941 Banker
        edit(BankerNpcAllRefs.hosidius_banker_f_east) {
            contentGroup = content.banker
        } // 6942 Banker
        edit(BankerNpcAllRefs.piscarilius_banker_1) { contentGroup = content.banker } // 6969 Banker
        edit(BankerNpcAllRefs.piscarilius_banker_2) { contentGroup = content.banker } // 6970 Banker
        edit(BankerNpcAllRefs.arceuus_banker_1_west) {
            contentGroup = content.banker
        } // 7057 Banker
        edit(BankerNpcAllRefs.arceuus_banker_1_east) {
            contentGroup = content.banker
        } // 7058 Banker
        edit(BankerNpcAllRefs.arceuus_banker_2_west) {
            contentGroup = content.banker
        } // 7059 Banker
        edit(BankerNpcAllRefs.arceuus_banker_2_east) {
            contentGroup = content.banker
        } // 7060 Banker
        edit(BankerNpcAllRefs.lovakengj_banker_f_west) {
            contentGroup = content.banker
        } // 7077 Banker
        edit(BankerNpcAllRefs.lovakengj_banker_f_north) {
            contentGroup = content.banker
        } // 7078 Banker
        edit(BankerNpcAllRefs.lovakengj_banker_f_east) {
            contentGroup = content.banker
        } // 7079 Banker
        edit(BankerNpcAllRefs.lovakengj_banker_f_south) {
            contentGroup = content.banker
        } // 7080 Banker
        edit(BankerNpcAllRefs.lovakengj_banker_m_east) {
            contentGroup = content.banker
        } // 7081 Banker
        edit(BankerNpcAllRefs.lovakengj_banker_m_south) {
            contentGroup = content.banker
        } // 7082 Banker
        edit(BankerNpcAllRefs.vampyre_banker_female) {
            contentGroup = content.banker
        } // 8321 Banker
        edit(BankerNpcAllRefs.vampyre_banker_male) { contentGroup = content.banker } // 8322 Banker
        edit(BankerNpcAllRefs.farming_guild_banker1) {
            contentGroup = content.banker
        } // 8589 Banker
        edit(BankerNpcAllRefs.farming_guild_banker2) {
            contentGroup = content.banker
        } // 8590 Banker
        edit(BankerNpcAllRefs.varrock_bank_doorguard) {
            contentGroup = content.banker
        } // 8666 Banker
        edit(BankerNpcAllRefs.prif_bankerm1) { contentGroup = content.banker } // 9127 Banker
        edit(BankerNpcAllRefs.prif_bankerm2) { contentGroup = content.banker } // 9128 Banker
        edit(BankerNpcAllRefs.prif_bankerm3) { contentGroup = content.banker } // 9129 Banker
        edit(BankerNpcAllRefs.prif_bankerm4) { contentGroup = content.banker } // 9130 Banker
        edit(BankerNpcAllRefs.prif_bankerf1) { contentGroup = content.banker } // 9131 Banker
        edit(BankerNpcAllRefs.prif_bankerf2) { contentGroup = content.banker } // 9132 Banker
        edit(BankerNpcAllRefs.tut2_bank_tutor) { contentGroup = content.banker } // 9484 Banker
        edit(BankerNpcAllRefs.darkm_banker_female) { contentGroup = content.banker } // 9718 Banker
        edit(BankerNpcAllRefs.darkm_banker_male) { contentGroup = content.banker } // 9719 Banker
        edit(BankerNpcAllRefs.wildy_hub_banker) { contentGroup = content.banker } // 10389 Banker
        edit(BankerNpcAllRefs.clan_hall_banker_0) { contentGroup = content.banker } // 10734 Banker
        edit(BankerNpcAllRefs.clan_hall_banker_1) { contentGroup = content.banker } // 10735 Banker
        edit(BankerNpcAllRefs.clan_hall_banker_2) { contentGroup = content.banker } // 10736 Banker
        edit(BankerNpcAllRefs.clan_hall_banker_3) { contentGroup = content.banker } // 10737 Banker
        edit(BankerNpcAllRefs.toa_bank_camel) { contentGroup = content.banker } // 11806 Bank Camel
        edit(BankerNpcAllRefs.cam_torum_banker_1) { contentGroup = content.banker } // 13044 Banker
        edit(BankerNpcAllRefs.cam_torum_banker_2) { contentGroup = content.banker } // 13045 Banker
        edit(BankerNpcAllRefs.cam_torum_banker_3) { contentGroup = content.banker } // 13046 Banker
        edit(BankerNpcAllRefs.cam_torum_banker_4) { contentGroup = content.banker } // 13047 Banker
        edit(BankerNpcAllRefs.hg_bank_buffalo) {
            contentGroup = content.banker
        } // 13128 Bank buffalo
        edit(BankerNpcAllRefs.hg_banker_dwarf) { contentGroup = content.banker } // 13129 Banker
        edit(BankerNpcAllRefs.varlamore_banker_s_1) {
            contentGroup = content.banker
        } // 13212 Banker
        edit(BankerNpcAllRefs.varlamore_banker_s_2) {
            contentGroup = content.banker
        } // 13213 Banker
        edit(BankerNpcAllRefs.varlamore_banker_s_3) {
            contentGroup = content.banker
        } // 13214 Banker
        edit(BankerNpcAllRefs.varlamore_banker_s_4) {
            contentGroup = content.banker
        } // 13215 Banker
        edit(BankerNpcAllRefs.varlamore_banker_n_1) {
            contentGroup = content.banker
        } // 13216 Banker
        edit(BankerNpcAllRefs.varlamore_banker_n_2) {
            contentGroup = content.banker
        } // 13217 Banker
        edit(BankerNpcAllRefs.varlamore_banker_n_3) {
            contentGroup = content.banker
        } // 13218 Banker
        edit(BankerNpcAllRefs.varlamore_banker_n_4) {
            contentGroup = content.banker
        } // 13219 Banker
        edit(BankerNpcAllRefs.varlamore_banker_e_1) {
            contentGroup = content.banker
        } // 13220 Banker
        edit(BankerNpcAllRefs.varlamore_banker_e_2) {
            contentGroup = content.banker
        } // 13221 Banker
        edit(BankerNpcAllRefs.varlamore_banker_e_3) {
            contentGroup = content.banker
        } // 13222 Banker
        edit(BankerNpcAllRefs.varlamore_banker_e_4) {
            contentGroup = content.banker
        } // 13223 Banker
        edit(BankerNpcAllRefs.varlamore_banker_w_1) {
            contentGroup = content.banker
        } // 13224 Banker
        edit(BankerNpcAllRefs.varlamore_banker_w_2) {
            contentGroup = content.banker
        } // 13225 Banker
        edit(BankerNpcAllRefs.varlamore_banker_w_3) {
            contentGroup = content.banker
        } // 13226 Banker
        edit(BankerNpcAllRefs.varlamore_banker_w_4) {
            contentGroup = content.banker
        } // 13227 Banker
        edit(BankerNpcAllRefs.mistrock_banker_1) { contentGroup = content.banker } // 13931 Banker
        edit(BankerNpcAllRefs.mistrock_banker_2) { contentGroup = content.banker } // 13932 Banker
        edit(BankerNpcAllRefs.auburnvale_banker_west_1) {
            contentGroup = content.banker
        } // 14671 Banker
        edit(BankerNpcAllRefs.auburnvale_banker_east_1) {
            contentGroup = content.banker
        } // 14672 Banker
        edit(BankerNpcAllRefs.auburnvale_banker_south_1) {
            contentGroup = content.banker
        } // 14673 Banker
        edit(BankerNpcAllRefs.auburnvale_banker_north_1) {
            contentGroup = content.banker
        } // 14674 Banker
        edit(BankerNpcAllRefs.tal_teklan_banker) { contentGroup = content.banker } // 14778 Banker
        edit(BankerNpcAllRefs.cw_banker_14847) { contentGroup = content.banker } // 14847 Banker
        edit(BankerNpcAllRefs.cw_banker_15496) { contentGroup = content.banker } // 15496 Banker
        edit(BankerNpcAllRefs.aide_tutor_banker) {
            contentGroup = content.banker_tutor
        } // 3227 Banker tutor
    }
}
