CREATE TABLE IF NOT EXISTS companion_ui_layout (
    character_id INTEGER PRIMARY KEY REFERENCES characters(id) ON DELETE CASCADE,
    x INTEGER NOT NULL DEFAULT 20,
    y INTEGER NOT NULL DEFAULT 20,
    width INTEGER NOT NULL DEFAULT 260,
    height INTEGER NOT NULL DEFAULT 92,
    scale_percent INTEGER NOT NULL DEFAULT 100,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
